/* Capcom's hand-written fill helpers (game/memset_2): word-fill in 16-byte blocks when the destination
 * is word aligned, byte tail otherwise; mtxclr_asm zeroes 3x4 float matrices. Assembly in the original
 * (the debug build has the unit as Capcom asm, the byte patterns show no compiler idiom); the functions
 * are whole-function asm() bodies, reproduced from the split object. */
#include "asm_regs.h"

asm("	.text\n"
    "	.balign 4\n");

/* void memset_asm(void *dst, int c, u32 n) */
asm("	.globl memset_asm\n"
    "	.type memset_asm,@function\n"
    "memset_asm:\n"
    "	cmplwi r5, 0xf\n"
    "	ble tail_set\n"
    "	andi. r0, r3, 0x3\n"
    "	bne tail_set\n"
    "	clrlwi r4, r4, 24\n"
    "	slwi r11, r4, 8\n"
    "	or r11, r11, r4\n"
    "	slwi r9, r11, 16\n"
    "	or r11, r11, r9\n"
    "	subi r3, r3, 0x4\n"
    "	srwi r12, r5, 4\n"
    "	andi. r5, r5, 0xf\n"
    "	mtctr r12\n"
    "block_set:\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	bdnz block_set\n"
    "	addi r3, r3, 0x4\n"
    "tail_set:\n"
    "	cmpwi r5, 0x0\n"
    "	beqlr\n"
    "	subi r3, r3, 0x1\n"
    "	mtctr r5\n"
    "byte_set:\n"
    "	stbu r4, 0x1(r3)\n"
    "	bdnz byte_set\n"
    "	blr\n"
    "	.size memset_asm,.-memset_asm\n");

/* void memclr_asm(void *dst, u32 n) */
asm("	.globl memclr_asm\n"
    "	.type memclr_asm,@function\n"
    "memclr_asm:\n"
    "	li r11, 0x0\n"
    "	cmplwi r4, 0xf\n"
    "	ble tail_clr\n"
    "	andi. r0, r3, 0x3\n"
    "	bne tail_clr\n"
    "	subi r3, r3, 0x4\n"
    "	srwi r12, r4, 4\n"
    "	andi. r4, r4, 0xf\n"
    "	mtctr r12\n"
    "block_clr:\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	bdnz block_clr\n"
    "	addi r3, r3, 0x4\n"
    "tail_clr:\n"
    "	cmpwi r4, 0x0\n"
    "	beqlr\n"
    "	subi r3, r3, 0x1\n"
    "	mtctr r4\n"
    "byte_clr:\n"
    "	stbu r11, 0x1(r3)\n"
    "	bdnz byte_clr\n"
    "	blr\n"
    "	.size memclr_asm,.-memclr_asm\n");

/* void mtxclr_asm(Mtx *dst, u32 count): zero `count` 3x4 float matrices */
asm("	.globl mtxclr_asm\n"
    "	.type mtxclr_asm,@function\n"
    "mtxclr_asm:\n"
    "	li r11, 0x0\n"
    "	subi r3, r3, 0x4\n"
    "	mtctr r4\n"
    "mtx_clr:\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	stwu r11, 0x4(r3)\n"
    "	bdnz mtx_clr\n"
    "	blr\n"
    "	.size mtxclr_asm,.-mtxclr_asm\n");
