# REL module configuration (the module list itself is the `modules:` block of config.yml; the
# per-module splits/symbols/sym_map/rel.json under config/G4BE08/modules/<mod>/ are generated by
# tools/gen_rel_config.py). Edit unit boundaries and Matching status by hand.

# Unit boundaries per module: list of (unit name, first function or .text offset[, source file under src/]). The debug
# build's Bio4.<mod>.sym has no per-object information, so a module is one unit "<mod>/<mod>.cpp"
# unless listed here. Data sections are attributed to units by the relocations from the unit's code
# (see the tool). A third element names a source shared by several modules (the same object is
# linked into each of them).
#
# Every st2_* module ends with the same st2.cpp object (__FILE__ "D:/Bio4/Prog/st2.cpp": set/setTbl
# register all stage-2 room Init/Main pairs in St2_data_tbl, then the SN REL entry points _prolog
# (ctors, setTbl), _epilog (dtors) and _unresolved (HALT)). st1_*/st4_0 have st1.cpp/st4.cpp the same way.
_ST2 = ("st2.cpp", "set", "st2/st2.cpp")
_ST1 = ("st1.cpp", "set", "st1/st1.cpp")
_ST4 = ("st4.cpp", "set", "st4/st4.cpp")
# Stage modules: every REL starts with the module's copy of em_wrap.cpp (cEmControl/cEmPatrol/cEmGuard,
# the cEmWrap enemy handle with its ~50 in-class members, the free setEm/SceCkFindPL; no __FILE__ string;
# src/st/em_wrap.cpp). The original REL link dead-stripped it at function level like the DOL: only the
# members the module's rooms (transitively) call survive, in declaration order, while every string and
# constant pool stays (.rodata 0..0xAE8 in all modules; st2_4/st4_0 were built with a later revision
# without the "cEmControl::SetPatrol" message, src/st/em_wrap_v2.cpp, 0xAC4). st1_0 uses none of it
# (.text empty, strings only). st2_0/st2_3/st4_0 then carry cSceObj.cpp (D:/Bio4/Prog/cSceObj.cpp,
# stripped the same way: st2_0 lacks the *Move1_ang/*Move3_y/setStart members). Then one object per room
# (D:/Bio4/Prog/rNNN.cpp; sources under src/st1/, src/st2/, src/st4/ because r102/r103/r108 are the same
# object in st1_1 and st1_3), then st1.cpp/st2.cpp/st4.cpp. Room .rodata starts are pinned at the room's
# first header string (cFlag.set()/atari.h/event.h/map_obj.h..., emitted at parse time, never referenced).
UNITS = {
    "st1_0": [
        ("st1_0/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_0/r100.cpp", "R100Init", "st1/r100.cpp", {".rodata": 0xae8}),
        ("st1_0/r120.cpp", "R120Init", "st1/r120.cpp", {".rodata": 0x10f0}),
        ("st1_0/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_1": [
        ("st1_1/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_1/r101.cpp", "R101Init", "st1/r101.cpp", {".rodata": 0xae8}),
        ("st1_1/r102.cpp", "R102Init", "st1/r102.cpp", {".rodata": 0xeb8}),
        ("st1_1/r103.cpp", "R103Init", "st1/r103.cpp", {".rodata": 0x1098}),
        ("st1_1/r104.cpp", "R104Init", "st1/r104.cpp", {".rodata": 0x11e0}),
        ("st1_1/r105.cpp", "R105Init", "st1/r105.cpp", {".rodata": 0x1488}),
        ("st1_1/r106.cpp", "R106Init", "st1/r106.cpp", {".rodata": 0x17a8}),
        ("st1_1/r107.cpp", "R107Init", "st1/r107.cpp", {".rodata": 0x1a84}),
        ("st1_1/r108.cpp", "R108Init", "st1/r108.cpp", {".rodata": 0x1c40}),
        ("st1_1/r109.cpp", "R109Init", "st1/r109.cpp", {".rodata": 0x1e50}),
        ("st1_1/r10a.cpp", "EmSetNormal", "st1/r10a.cpp", {".rodata": 0x1fe4}),
        ("st1_1/r10b.cpp", "R10bInit", "st1/r10b.cpp", {".rodata": 0x21c4}),
        ("st1_1/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_2": [
        ("st1_2/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_2/r10c.cpp", "R10cInit", "st1/r10c.cpp", {".rodata": 0xae8}),
        ("st1_2/r10d.cpp", "R10dInit", "st1/r10d.cpp", {".rodata": 0xe40}),
        ("st1_2/r10e.cpp", "R10eInit", "st1/r10e.cpp", {".rodata": 0xe80}),
        ("st1_2/r119.cpp", "R119Init", "st1/r119.cpp", {".rodata": 0xec0}),
        ("st1_2/r11a.cpp", "R11aInit", "st1/r11a.cpp", {".rodata": 0x1224}),
        ("st1_2/r11b.cpp", "R11bInit", "st1/r11b.cpp", {".rodata": 0x13c8}),
        ("st1_2/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_3": [
        ("st1_3/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_3/r102.cpp", "R102Init", "st1/r102.cpp", {".rodata": 0xae8}),
        ("st1_3/r103.cpp", "R103Init", "st1/r103.cpp", {".rodata": 0xcc8}),
        ("st1_3/r108.cpp", "R108Init", "st1/r108.cpp", {".rodata": 0xe10}),
        ("st1_3/r10f.cpp", "R10fInit", "st1/r10f.cpp", {".rodata": 0x1020}),
        ("st1_3/r111.cpp", "R111Init", "st1/r111.cpp", {".rodata": 0x12ac}),
        ("st1_3/r112.cpp", "R112Init", "st1/r112.cpp", {".rodata": 0x144c}),
        ("st1_3/r113.cpp", "R113Init", "st1/r113.cpp", {".rodata": 0x15ac}),
        ("st1_3/r117.cpp", "R117Init", "st1/r117.cpp", {".rodata": 0x1798}),
        ("st1_3/r118.cpp", "R118Init", "st1/r118.cpp", {".rodata": 0x1b24}),
        ("st1_3/r11c.cpp", "R11cInit", "st1/r11c.cpp", {".rodata": 0x1cc8}),
        ("st1_3/r11d.cpp", "R11dInit", "st1/r11d.cpp", {".rodata": 0x20c8}),
        ("st1_3/r11e.cpp", "R11eInit", "st1/r11e.cpp", {".rodata": 0x22e0}),
        ("st1_3/r11f.cpp", "R11fInit", "st1/r11f.cpp", {".rodata": 0x2540}),
        ("st1_3/" + _ST1[0], *_ST1[1:]),
    ],
    "st2_0": [
        ("st2_0/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_0/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st2_0/r200.cpp", "R200Init", "st2/r200.cpp", {".rodata": 0xb80}),
        ("st2_0/r201.cpp", "R201Init", "st2/r201.cpp", {".rodata": 0xcf8}),
        ("st2_0/r202.cpp", "R202Init", "st2/r202.cpp", {".rodata": 0xf60}),
        ("st2_0/r203.cpp", "R203Init", "st2/r203.cpp", {".rodata": 0x1248}),
        ("st2_0/r207.cpp", "R207Init", "st2/r207.cpp", {".rodata": 0x1508}),
        ("st2_0/r208.cpp", 0xDF38, "st2/r208.cpp", {".rodata": 0x16e0}),
        ("st2_0/r210.cpp", "asl_wait", "st2/r210.cpp", {".rodata": 0x1b28}),
        ("st2_0/r222.cpp", "R222Init", "st2/r222.cpp", {".rodata": 0x1c40}),
        ("st2_0/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_1": [
        ("st2_1/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_1/r204.cpp", "R204Init", "st2/r204.cpp", {".rodata": 0xae8}),
        ("st2_1/r205.cpp", "R205Init", "st2/r205.cpp", {".rodata": 0xe68}),
        ("st2_1/r206.cpp", "R206Init", "st2/r206.cpp", {".rodata": 0x10b8}),
        ("st2_1/r209.cpp", "R209Init", "st2/r209.cpp", {".rodata": 0x1410}),
        ("st2_1/r20a.cpp", "R20aInit", "st2/r20a.cpp", {".rodata": 0x182c}),
        ("st2_1/r20b.cpp", "R20bInit", "st2/r20b.cpp", {".rodata": 0x1918}),
        ("st2_1/r20c.cpp", "R20cInit", "st2/r20c.cpp", {".rodata": 0x1c50}),
        ("st2_1/r20d.cpp", "R20dInit", "st2/r20d.cpp", {".rodata": 0x1e48}),
        ("st2_1/r20e.cpp", "R20eInit", "st2/r20e.cpp", {".rodata": 0x2280}),
        ("st2_1/r20f.cpp", "R20fInit", "st2/r20f.cpp", {".rodata": 0x24f8}),
        ("st2_1/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_2": [
        ("st2_2/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_2/r211.cpp", "R211Init", "st2/r211.cpp", {".rodata": 0xae8}),
        ("st2_2/r212.cpp", "R212Init", "st2/r212.cpp", {".rodata": 0xc80}),
        ("st2_2/r213.cpp", "R213Init", "st2/r213.cpp", {".rodata": 0xfb8}),
        ("st2_2/r214.cpp", "R214Init", "st2/r214.cpp", {".rodata": 0x11d8}),
        ("st2_2/r215.cpp", "R215Init", "st2/r215.cpp", {".rodata": 0x14dc}),
        ("st2_2/r216.cpp", "R216Init", "st2/r216.cpp", {".rodata": 0x177c}),
        ("st2_2/r217.cpp", "R217Init", "st2/r217.cpp", {".rodata": 0x1850}),
        ("st2_2/r218.cpp", "R218Init", "st2/r218.cpp", {".rodata": 0x1a90}),
        ("st2_2/r219.cpp", "R219Init", "st2/r219.cpp", {".rodata": 0x1b48}),
        ("st2_2/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_3": [
        ("st2_3/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_3/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st2_3/r21a.cpp", "R21aInit", "st2/r21a.cpp", {".rodata": 0xb80}),
        ("st2_3/r21b.cpp", "R21bInit", "st2/r21b.cpp", {".rodata": 0xde8, ".data": 0xA8}),
        ("st2_3/r21d.cpp", "R21dInit", "st2/r21d.cpp", {".rodata": 0xf08}),
        ("st2_3/r220.cpp", "R220Init", "st2/r220.cpp", {".rodata": 0x11ac}),
        ("st2_3/r221.cpp", "R221Init", "st2/r221.cpp", {".rodata": 0x1268}),
        ("st2_3/r223.cpp", "R223Init", "st2/r223.cpp", {".rodata": 0x1520}),
        ("st2_3/r224.cpp", "R224Init", "st2/r224.cpp", {".rodata": 0x1788}),
        ("st2_3/r225.cpp", "R225Init", "st2/r225.cpp", {".rodata": 0x1a80}),
        ("st2_3/r226.cpp", "R226Init", "st2/r226.cpp", {".rodata": 0x1cd0}),
        ("st2_3/r227.cpp", "R227Init", "st2/r227.cpp", {".rodata": 0x2140}),
        ("st2_3/r228.cpp", "R228Init", "st2/r228.cpp", {".rodata": 0x2430}),
        ("st2_3/r229.cpp", "R229Init", "st2/r229.cpp", {".rodata": 0x26bc}),
        ("st2_3/r22a.cpp", "R22aInit", "st2/r22a.cpp", {".rodata": 0x28f8}),
        ("st2_3/r22b.cpp", "R22bInit", "st2/r22b.cpp", {".rodata": 0x2a88}),
        ("st2_3/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_4": [
        ("st2_4/em_wrap.cpp", None, "st/em_wrap_v2.cpp", {".rodata": 0x0}),
        ("st2_4/r22c.cpp", "R22cInit", "st2/r22c.cpp", {".rodata": 0xac4}),
        ("st2_4/" + _ST2[0], *_ST2[1:]),
    ],
    "st4_0": [
        ("st4_0/em_wrap.cpp", None, "st/em_wrap_v2.cpp", {".rodata": 0x0}),
        ("st4_0/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xac4}),
        ("st4_0/r400.cpp", "R400Init", "st4/r400.cpp", {".rodata": 0xb60}),
        ("st4_0/r402.cpp", "R402Init", "st4/r402.cpp", {".rodata": 0xdf0}),
        ("st4_0/r403.cpp", "R403Init", "st4/r403.cpp", {".rodata": 0x1000}),
        ("st4_0/r404.cpp", "R404Init", "st4/r404.cpp", {".rodata": 0x1338}),
        ("st4_0/r405.cpp", "snd_tbl_set", "st4/r405.cpp", {".rodata": 0x1478}),
        ("st4_0/r406.cpp", "R406Init", "st4/r406.cpp", {".rodata": 0x16dc}),
        ("st4_0/r40a.cpp", "r40a_DuraluminCaseOpen", "st4/r40a.cpp", {".rodata": 0x17f0}),
        ("st4_0/r40b.cpp", "R40bInit", "st4/r40b.cpp", {".rodata": 0x1888}),
        ("st4_0/r40c.cpp", "R40cInit", "st4/r40c.cpp", {".rodata": 0x19e8}),
        ("st4_0/r40d.cpp", "R40dInit", "st4/r40d.cpp", {".rodata": 0x1b8c}),
        ("st4_0/r40e.cpp", "R40eInit", "st4/r40e.cpp", {".rodata": 0x1cf8}),
        ("st4_0/r40f.cpp", "R40fInit", "st4/r40f.cpp", {".rodata": 0x2008}),
        ("st4_0/r410.cpp", "R410Init", "st4/r410.cpp", {".rodata": 0x20b4}),
        ("st4_0/r411.cpp", "R411Init", "st4/r411.cpp", {".rodata": 0x2130}),
        # st4.cpp includes map_obj.h/light.h/widget.h/atari.h (their strings + its cManager<cLight> block)
        ("st4_0/" + _ST4[0], *_ST4[1:], {".rodata": 0x21AC}),
    ],
    # Debug tool modules: <tool>.cpp, then the tool library objects t_prim.cpp / t_util.cpp (the full
    # versions of the DOL's game/t_prim, game/t_util, which the DOL link dead-stripped), then the shared
    # tools.cpp (D:/Bio4/Prog/tools.cpp: _prolog runs the ctors and ToolsTask, which dispatches
    # DebugMenuSelected to the Tool* entry of every tool module). Each object that includes light.h
    # carries its own cManager<cLight> instantiations behind its code (see LINKONCE below).
    # tools.cpp is also the last object of t_camera/t_light/t_sce/t_event (same bytes); t_esp/Tools/t_id
    # have their linkonce orphan sections behind it and t_movie has other objects after it.
    "t_camera": [("t_camera/t_camera.cpp", None), ("t_camera/tools.cpp", "_prolog", "tools/tools.cpp")],
    "t_light": [("t_light/t_light.cpp", None), ("t_light/tools.cpp", "_prolog", "tools/tools.cpp")],
    "t_sce": [("t_sce/t_sce.cpp", None), ("t_sce/tools.cpp", "_prolog", "tools/tools.cpp")],
    "t_event": [("t_event/t_event.cpp", None), ("t_event/tools.cpp", "_prolog", "tools/tools.cpp")],
    "t_emlist": [
        ("t_emlist/t_emlist.cpp", None),
        ("t_emlist/t_prim.cpp", "TprimInitEnv2D3D", "tools/t_prim.cpp"),
        # t_util's header strings (map_obj.h/light.h/widget.h) and its .data (old_menu, the menu
        # statics) are not addressed by its code
        ("t_emlist/t_util.cpp", "TutilInitDefault", "tools/t_util.cpp", {".rodata": 0x14E0, ".data": 0x29FC}),
        ("t_emlist/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
}
# The 16 Ganado modules (em10..em20) are the same em10.cpp ("D:/Bio4/Prog/em10.cpp": cEm10 and its
# em10*/em1c* helpers, .text 0-0x43518 + 0x3B8 bytes of template instantiations, .rodata 0-0x1EC4,
# all of .data/.bss, byte-identical in every module), then two small per-enemy objects whose names
# are not in the binary: the entry file (_prolog: OSReport("em10 prolog Ok\n") in every module,
# EmInitFunc = EmXXInit, EmSetFunc = EmXXSet; _epilog, _unresolved) and EmXXInit/Set/WeaponSet.
# They must be separate objects: ngcld -r adds an input section's displacement to ADDR16/ADDR32
# fields that reference a global defined in the same object, and the original fields are 0.
# em1d/em1e/em1f/em20 include light.h in the tail (cManager<cLight> code the .sym skips after
# EmXXWeaponSet) and carry an unreferenced "D:/Bio4/Prog/light.h" string right after em10.cpp's
# .rodata, so the entry unit's .rodata start is pinned (4th element) at em10.cpp's end.
for _em in ["em10", "em11", "em12", "em13", "em14", "em15", "em16", "em17", "em19", "em1a", "em1b",
            "em1c", "em1d", "em1e", "em1f", "em20"]:
    UNITS[_em] = [
        (f"{_em}/em10.cpp", None, "em10/em10.cpp"),
        (f"{_em}/{_em}_prolog.cpp", "_prolog", None, {".rodata": 0x1EC4}),
        (f"{_em}/{_em}_set.cpp", f"Em{_em[2:]}Init"),
    ]

# Module units the original REL link dead-stripped at function level (bodies gone, strings and constant
# pools kept, like the DOL's SDK/dead game functions): tools/strip_unused.py --module removes every
# function the module's sym_map.tsv does not list for the unit (configure.py adds the post-build step).
STRIP_UNUSED = {
    f"{_m}/em_wrap.cpp" for _m in ["st1_0", "st1_1", "st1_2", "st1_3", "st2_0", "st2_1", "st2_2", "st2_3", "st2_4", "st4_0"]
} | {f"{_m}/cSceObj.cpp" for _m in ["st2_0", "st2_3", "st4_0"]}

# Units whose compiled object replaces the split object in the REL link.
MATCHING = {
    "st1_0/em_wrap.cpp": True,
    "st2_4/em_wrap.cpp": True,
    "st1_2/r10d.cpp": True,
    "st1_2/r10e.cpp": True,
    "st1_2/r11a.cpp": True,
    "st1_1/r109.cpp": True,
    "st1_1/r107.cpp": True,
    "st1_0/st1.cpp": True,
    "st1_1/st1.cpp": True,
    "st1_2/st1.cpp": True,
    "st1_3/st1.cpp": True,
    "st2_0/st2.cpp": True,
    "st2_1/st2.cpp": True,
    "st2_2/st2.cpp": True,
    "st2_3/st2.cpp": True,
    "st2_4/st2.cpp": True,
    "st4_0/st4.cpp": True,
    "t_emlist/t_emlist.cpp": True,
    "t_emlist/t_prim.cpp": True,
    "t_emlist/t_util.cpp": True,
    "t_emlist/tools.cpp": True,
    "t_camera/tools.cpp": True,
    "t_light/tools.cpp": True,
    "t_sce/tools.cpp": True,
    "t_event/tools.cpp": True,
}
