# Generated by tools/gen_config.py from Bio4.sym. Edit Matching status by hand.
UNITS = [
    "lib/__start.c",
    "game/cam_ctrl.cpp",
    "game/card.cpp",
    "game/ctrl01.cpp",
    "game/ctrl11.cpp",
    "game/ctrl12.cpp",
    "game/ctrl14.cpp",
    "game/emBar.cpp",
    "game/emwep.cpp",
    "game/item.cpp",
    "game/light_area.cpp",
    "game/lightInfo.cpp",
    "game/lightPath.cpp",
    "game/map_obj.cpp",
    "game/mercenaries.cpp",
    "game/merchant.cpp",
    "game/mes.cpp",
    "game/obj13.cpp",
    "game/obj14.cpp",
    "game/obj15.cpp",
    "game/obj16.cpp",
    "game/obj19.cpp",
    "game/obj1b.cpp",
    "game/obj1c.cpp",
    "game/obj1d.cpp",
    "game/obj20.cpp",
    "game/obj26.cpp",
    "game/objBull.cpp",
    "game/objGondola.cpp",
    "game/objMissile.cpp",
    "game/objPillar.cpp",
    "game/objRobo.cpp",
    "game/objRocket.cpp",
    "game/objSubWep.cpp",
    "game/objTrolley.cpp",
    "game/objWep.cpp",
    "game/objYagura.cpp",
    "game/option.cpp",
    "game/pl_ashley.cpp",
    "game/pl_debug.cpp",
    "game/pl_dmg.cpp",
    "game/pl_event.cpp",
    "game/pl_knife.cpp",
    "game/pl_leon.cpp",
    "game/pl_npc.cpp",
    "game/pl_push.cpp",
    "game/player.cpp",
    "game/snd.cpp",
    "game/sscrn.cpp",
    "lib/ppcdown.c",
    "lib/fileserver.c",
    "lib/proview.c",
    "lib/tealeaf.c",
    "lib/FSasync.c",
    "lib/sndvd.c",
    "lib/e_atan2.c",
    "lib/e_log10.c",
    "lib/s_atan.c",
    "lib/s_fabs.c",
    "lib/s_tan.c",
    "lib/ef_acos.c",
    "lib/ef_asin.c",
    "lib/ef_atan2.c",
    "lib/ef_sqrt.c",
    "lib/sf_atan.c",
    "lib/sf_cos.c",
    "lib/sf_fabs.c",
    "lib/sf_sin.c",
    "lib/sf_tan.c",
    "lib/k_tan.c",
    "lib/e_log.c",
    "lib/e_rem_pio2.c",
    "lib/kf_cos.c",
    "lib/kf_sin.c",
    "lib/kf_tan.c",
    "lib/ef_rem_pio2.c",
    "lib/k_rem_pio2.c",
    "lib/s_floor.c",
    "lib/kf_rem_pio2.c",
    "lib/sf_floor.c",
    "lib/s_scalbn.c",
    "lib/sf_scalbn.c",
    "lib/s_copysign.c",
    "lib/sf_copysign.c",
    "game/sprintf.c",
    "game/sscanf.c",
    "game/vfscanf.c",
    "game/atof.c",
    "game/atoi.c",
    "game/exit.c",
    "game/mbtowc_r.c",
    "game/qsort.c",
    "game/strtod2.c",
    "game/strtoul.c",
    "game/memcpy.c",
    "game/memset.c",
    "game/strcat.c",
    "game/strchr.c",
    "game/strcmp.c",
    "game/strcpy.c",
    "game/strlen.c",
    "game/strncmp.c",
    "game/strncpy.c",
    "game/strpbrk.c",
    "game/strrchr.c",
    "game/strspn.c",
    "game/strstr.c",
    "game/vfprintf.c",
    "game/vfiprintf.c",
    "game/strtol.c",
    "game/isdigit.c",
    "game/isspace.c",
    "game/errno.c",
    "game/locale.c",
    "game/math_support.c",
    "game/fread.c",
    "game/refill.c",
    "game/ungetc.c",
    "game/memchr.c",
    "game/fflush.c",
    "game/fopen.c",
    "game/fwalk.c",
    "game/makebuf.c",
    "game/stdio.c",
    "game/closer.c",
    "game/fstatr.c",
    "game/lseekr.c",
    "game/readr.c",
    "game/writer.c",
    "lib/_ashldi3.c",
    "lib/_ashrdi3.c",
    "lib/_divdi3.c",
    "lib/_exit.c",
    "lib/_lshrdi3.c",
    "lib/_moddi3.c",
    "lib/_pure.c",
    "lib/_udivdi3.c",
    "lib/_umoddi3.c",
    "lib/_eh.c",
    "lib/PPCArch.c",
    "lib/OS.c",
    "lib/OSAlarm.c",
    "lib/OSArena.c",
    "lib/OSAudioSystem.c",
    "lib/OSCache.c",
    "lib/OSContext.c",
    "lib/OSError.c",
    "lib/OSExec.c",
    "lib/OSInterrupt.c",
    "lib/OSLink.c",
    "lib/OSMemory.c",
    "lib/OSReboot.c",
    "lib/OSReset.c",
    "lib/OSResetSW.c",
    "lib/OSRtc.c",
    "lib/OSSync.c",
    "lib/OSThread.c",
    "lib/OSTime.c",
    "lib/__ppc_eabi_init.c",
    "lib/OSMutex.c",
    "lib/EXIBios.c",
    "lib/EXIUart.c",
    "lib/SIBios.c",
    "lib/SISamplingRate.c",
    "lib/db.c",
    "lib/mtx.c",
    "lib/mtxvec.c",
    "lib/mtx44.c",
    "lib/vec.c",
    "lib/quat.c",
    "lib/dvdfs.c",
    "lib/dvd.c",
    "lib/dvdqueue.c",
    "lib/dvderror.c",
    "lib/dvdidutils.c",
    "lib/dvdFatal.c",
    "lib/fstload.c",
    "lib/dvdlow.c",
    "lib/vi.c",
    "lib/Pad.c",
    "lib/ai.c",
    "lib/ar.c",
    "lib/arq.c",
    "lib/AX.c",
    "lib/AXAlloc.c",
    "lib/AXAux.c",
    "lib/AXCL.c",
    "lib/AXOut.c",
    "lib/AXSPB.c",
    "lib/AXVPB.c",
    "lib/AXProf.c",
    "lib/axfx.c",
    "lib/mix.c",
    "lib/axart.c",
    "lib/axartsound.c",
    "lib/axartcents.c",
    "lib/axartenv.c",
    "lib/axartlfo.c",
    "lib/axart3d.c",
    "lib/axartlpf.c",
    "lib/syn.c",
    "lib/synctrl.c",
    "lib/synenv.c",
    "lib/synlfo.c",
    "lib/synmix.c",
    "lib/synpitch.c",
    "lib/synsample.c",
    "lib/synvoice.c",
    "lib/synwt.c",
    "lib/seq.c",
    "lib/dsp.c",
    "lib/dsp_debug.c",
    "lib/dsp_task.c",
    "lib/CARDBios.c",
    "lib/CARDBlock.c",
    "lib/CARDDir.c",
    "lib/CARDCheck.c",
    "lib/CARDMount.c",
    "lib/CARDFormat.c",
    "lib/CARDOpen.c",
    "lib/CARDCreate.c",
    "lib/CARDRead.c",
    "lib/CARDWrite.c",
    "lib/CARDDelete.c",
    "lib/CARDStat.c",
    "lib/CARDNet.c",
    "lib/CARDUnlock.c",
    "lib/CARDRdwr.c",
    "lib/GXAttr.c",
    "lib/GXGeometry.c",
    "lib/GXLight.c",
    "lib/GXTexture.c",
    "lib/GXBump.c",
    "lib/GXTev.c",
    "lib/GXPixel.c",
    "lib/GXTransform.c",
    "lib/GXInit.c",
    "lib/GXFifo.c",
    "lib/GXMisc.c",
    "lib/GXFrameBuf.c",
    "lib/GXPerf.c",
    "lib/texPalette.c",
    "lib/AmcExi2Stubs.c",
    "lib/DebuggerDriver.c",
    "game/snd_efx.cpp",
    "game/snd_iss0.cpp",
    "game/snd_iss1.cpp",
    "game/snd_main.cpp",
    "game/snd_seq0.cpp",
    "game/snd_seq1.cpp",
    "game/snd_seq2.cpp",
    "game/snd_seq3.cpp",
    "game/snd_str0.cpp",
    "game/snd_str1.cpp",
    "game/snd_str2.cpp",
    "game/snd_str3.cpp",
    "game/snd_str4.cpp",
    "game/snd_sub0.cpp",
    "game/snd_sub1.cpp",
    "game/snd_sub2.cpp",
    "game/snd_sub3.cpp",
    "game/snd_iss2.cpp",
    "game/snd_iss3.cpp",
    "game/snd_iss4.cpp",
    "lib/adx_tlk.c",
    "lib/adx_tsvr.c",
    "lib/adx_rnaa.c",
    "lib/lsc.c",
    "lib/lsc_ini.c",
    "lib/lsc_svr.c",
    "lib/sj_rbf.c",
    "lib/sj_utl.c",
    "lib/sj_err.c",
    "lib/svm.c",
    "lib/ax_rna.c",
    "lib/rna_res.c",
    "lib/adx_inis.c",
    "lib/adx_sjd.c",
    "lib/adx_bahx.c",
    "lib/adx_bsc.c",
    "lib/adx_bsps.c",
    "lib/adx_amp.c",
    "lib/adx_crs.c",
    "lib/adx_dcd.c",
    "lib/adx_errs.c",
    "lib/adx_fsvr.c",
    "lib/adx_stmc.c",
    "lib/adx_xpnd.c",
    "lib/adx_mgc.c",
    "lib/adx_dcd5.c",
    "lib/adx_fini.c",
    "lib/adx_fs.c",
    "lib/cri_cvfs.c",
    "lib/lsc_err.c",
    "lib/lsc_crs.c",
    "lib/sj_crs.c",
    "lib/sj_mem.c",
    "lib/sj_uni.c",
    "lib/rna_err.c",
    "lib/rna_crs.c",
    "lib/adx_bwav.c",
    "lib/adx_baif.c",
    "lib/adx_bau.c",
    "lib/adx_fcch.c",
    "game/act_btn.cpp",
    "game/area.cpp",
    "game/at_mod.cpp",
    "game/at_sub.cpp",
    "game/atari.cpp",
    "game/atariInfo.cpp",
    "game/block.cpp",
    "game/cam_extra.cpp",
    "game/cam_motion.cpp",
    "game/cam_qfps.cpp",
    "game/cam_sys.cpp",
    "game/camera.cpp",
    "game/cDataSwap.cpp",
    "game/cMotBase.cpp",
    "game/cockpit.cpp",
    "game/cons.cpp",
    "game/cString.cpp",
    "game/ctrl.cpp",
    "game/datactrl.cpp",
    "game/db_cam.cpp",
    "game/db_log.cpp",
    "game/db_menu.cpp",
    "game/dbmodule.cpp",
    "game/debug.cpp",
    "game/dmg.cpp",
    "game/dvd.cpp",
    "game/eff_sys.cpp",
    "game/em.cpp",
    "game/em_cloth.cpp",
    "game/em_dm_val.cpp",
    "game/em_set.cpp",
    "game/em_sub.cpp",
    "game/emBarred.cpp",
    "game/embarrel.cpp",
    "game/embox.cpp",
    "game/emdata.cpp",
    "game/emdoor.cpp",
    "game/emhit.cpp",
    "game/emitem.cpp",
    "game/emmine.cpp",
    "game/emrack.cpp",
    "game/emrock.cpp",
    "game/emshield.cpp",
    "game/emswitch.cpp",
    "game/emtorch.cpp",
    "game/emtree.cpp",
    "game/emwindow.cpp",
    "game/eprintf.cpp",
    "game/esp.cpp",
    "game/esp_app.cpp",
    "game/esp_efm.cpp",
    "game/esp_sub.cpp",
    "game/espgen.cpp",
    "game/espgen00.cpp",
    "game/espgen01.cpp",
    "game/espgen02.cpp",
    "game/espgen10.cpp",
    "game/espgen40.cpp",
    "game/Espgen42.cpp",
    "game/Espgen43.cpp",
    "game/espgen44.cpp",
    "game/espgen45.cpp",
    "game/est.cpp",
    "game/EtcModel.cpp",
    "game/event.cpp",
    "game/examine.cpp",
    "game/fade.cpp",
    "game/file.cpp",
    "game/file_app.cpp",
    "game/filter01.cpp",
    "game/filter05.cpp",
    "game/filter06.cpp",
    "game/filter0a.cpp",
    "game/filter0b.cpp",
    "game/flr_at.cpp",
    "game/game.cpp",
    "game/geometry.cpp",
    "game/gx_sub.cpp",
    "game/hermite.cpp",
    "game/id_sys.cpp",
    "game/id_tex.cpp",
    "game/item_model.cpp",
    "game/libgpu.cpp",
    "game/light.cpp",
    "game/light01.cpp",
    "game/light02.cpp",
    "game/light03.cpp",
    "game/light04.cpp",
    "game/light05.cpp",
    "game/light06.cpp",
    "game/light07.cpp",
    "game/light08.cpp",
    "game/light10.cpp",
    "game/main.cpp",
    "game/main_mem.cpp",
    "game/main_sub.cpp",
    "game/math_sub.cpp",
    "game/memset_2.s",
    "game/model.cpp",
    "game/motion.cpp",
    "game/obj.cpp",
    "game/obj00.cpp",
    "game/obj01.cpp",
    "game/obj02.cpp",
    "game/obj03.cpp",
    "game/obj04.cpp",
    "game/obj05.cpp",
    "game/obj06.cpp",
    "game/obj08.cpp",
    "game/obj09.cpp",
    "game/obj10.cpp",
    "game/obj12.cpp",
    "game/obj18.cpp",
    "game/pad.cpp",
    "game/path.cpp",
    "game/pendulum.cpp",
    "game/pl_body.cpp",
    "game/pl_class.cpp",
    "game/pl_cloth.cpp",
    "game/pl_sub.cpp",
    "game/pl_wep.cpp",
    "game/puzzle.cpp",
    "game/quake.cpp",
    "game/read.cpp",
    "game/rnd.cpp",
    "game/room_jmp.cpp",
    "game/room_tex.cpp",
    "game/roomdata.cpp",
    "game/route_ck.cpp",
    "game/sce_at.cpp",
    "game/sce_com.cpp",
    "game/sce_sys.cpp",
    "game/scheduler.cpp",
    "game/scroll.cpp",
    "game/se_at.cpp",
    "game/shadow.cpp",
    "game/shape.cpp",
    "game/sofdec.cpp",
    "game/stage.cpp",
    "game/sub2.cpp",
    "game/t_bugcheck.cpp",
    "game/t_flag.cpp",
    "game/t_log.cpp",
    "game/t_option.cpp",
    "game/t_page.cpp",
    "game/t_prim.cpp",
    "game/t_sc_shot.cpp",
    "game/t_util.cpp",
    "game/TexRender.cpp",
    "game/texture.cpp",
    "game/title.cpp",
    "game/TmpBuf.cpp",
    "game/trans.cpp",
    "game/trans_lit.cpp",
    "game/trans_ot.cpp",
    "game/tv_mode.cpp",
    "game/view.cpp",
    "game/xml.cpp",
    "game/yz2code.cpp",
    "game/at_sub2.cpp",
    "game/cinesco.cpp",
    "game/cloth.cpp",
    "game/db_work.cpp",
    "game/emobj.cpp",
    "game/esp00.cpp",
    "game/esp01.cpp",
    "game/esp02.cpp",
    "game/esp03.cpp",
    "game/esp04.cpp",
    "game/esp05.cpp",
    "game/esp06.cpp",
    "game/esp07.cpp",
    "game/esp08.cpp",
    "game/esp09.cpp",
    "game/esp0a.cpp",
    "game/esp0b.cpp",
    "game/esp0c.cpp",
    "game/esp0d.cpp",
    "game/esp0e.cpp",
    "game/esp0f.cpp",
    "game/esp10.cpp",
    "game/esp11.cpp",
    "game/esp12.cpp",
    "game/esp13.cpp",
    "game/esp14.cpp",
    "game/esp15.cpp",
    "game/esp16.cpp",
    "game/esp17.cpp",
    "game/esp18.cpp",
    "game/esp19.cpp",
    "game/esp1a.cpp",
    "game/esp1b.cpp",
    "game/esp3f.cpp",
    "game/esp40.cpp",
    "game/esp41.cpp",
    "game/esp42.cpp",
    "game/esp43.cpp",
    "game/esp44.cpp",
    "game/esp45.cpp",
    "game/esp46.cpp",
    "game/esp47.cpp",
    "game/esp48.cpp",
    "game/esp49.cpp",
    "game/esp4a.cpp",
    "game/esp4b.cpp",
    "game/esp4c.cpp",
    "game/esp4d.cpp",
    "game/esp4e.cpp",
    "game/esp4f.cpp",
    "game/et00.cpp",
    "game/exception.cpp",
    "game/filter.cpp",
    "game/filter00.cpp",
    "game/filter02.cpp",
    "game/filter03.cpp",
    "game/filter04.cpp",
    "game/filter07.cpp",
    "game/filter08.cpp",
    "game/filter09.cpp",
    "game/foot_shadow.cpp",
    "game/ik.cpp",
    "game/mirror.cpp",
    "game/yz2asm.s",
    "lib/dummy.c",
    "lib/e_pow.c",
    "lib/e_sqrt.c",
    "lib/s_cos.c",
    "lib/ef_pow.c",
    "lib/k_cos.c",
    "lib/k_sin.c",
    "game/tolower.c",
    "game/fprintf.c",
    "game/printf.c",
    "game/vprintf.c",
    "game/vsprintf.c",
    "game/memcmp.c",
    "game/memmove.c",
    "game/strcspn.c",
    "game/strncat.c",
    "lib/__main.c",
    "lib/OSAlloc.c",
    "lib/OSFont.c",
    "lib/OSSemaphore.c",
    "lib/OSStopwatch.c",
    "lib/mtx44vec.c",
    "lib/psmtx.c",
    "lib/Padclamp.c",
    "lib/reverb_hi.c",
    "lib/reverb_std.c",
    "lib/chorus.c",
    "lib/delay.c",
    "lib/reverb_hi_4ch.c",
    "lib/GXDraw.c",
    "lib/GXDisplayList.c",
    "lib/mwsfdfrm.c",
    "lib/mwsfdsvm.c",
    "lib/mwsfdsfx.c",
    "lib/mwsfdcre.c",
    "lib/mwsfdlib.c",
    "lib/mwsfdply.c",
    "lib/mwsfdset.c",
    "lib/mwsfdsvr.c",
    "lib/mwsfdsst.c",
    "lib/mwsfx_ARGB8888PLN.c",
    "lib/mwsfx_Y84C44.c",
    "lib/sud_lib.c",
    "lib/sfx_set.c",
    "lib/sfx_cnv.c",
    "lib/sfx_lib.c",
    "lib/sfx_alp.c",
    "lib/sfx_zmv.c",
    "lib/sfx_sud.c",
    "lib/sfx_cnv_to_ARGB8888PLN.c",
    "lib/sfx_cnv_to_Y84C44.c",
    "lib/sfx_YCC420PLN_to_ARGB8888PLN.c",
    "lib/sfx_YCC420PLN_to_Y84C44.c",
    "lib/sfd_adxt.c",
    "lib/sfd_aoap.c",
    "lib/sfd_buf.c",
    "lib/sfd_con.c",
    "lib/sfd_cre.c",
    "lib/sfd_hds.c",
    "lib/sfd_lib.c",
    "lib/sfd_mem.c",
    "lib/sfd_mps.c",
    "lib/sfd_mpv.c",
    "lib/sfd_mpvf.c",
    "lib/sfd_pl2.c",
    "lib/sfd_ply.c",
    "lib/sfd_pts.c",
    "lib/sfd_see.c",
    "lib/sfd_set.c",
    "lib/sfd_tim.c",
    "lib/sfd_trn.c",
    "lib/sfd_uo.c",
    "lib/sfd_vom.c",
    "lib/sfd_tmr.c",
    "lib/sfd_tst.c",
    "lib/sfh_main.c",
    "lib/cmptime.c",
    "lib/memsetd.c",
    "lib/muldiv.c",
    "lib/muldivr.c",
    "lib/uty_tmr.c",
    "lib/mwsfdrna.c",
    "lib/mwsfdrsc.c",
    "lib/mwsfdsl.c",
    "lib/mwstm.c",
    "lib/mwsfdsee.c",
    "lib/cftyp422_ppc.c",
    "lib/cftfx.c",
    "lib/cftcoladj.c",
    "lib/sfx_inf.c",
    "lib/mcp_not.c",
    "lib/mps_dec.c",
    "lib/mps_del.c",
    "lib/mps_get.c",
    "lib/mps_lib.c",
    "lib/mpv_deli.c",
    "lib/mpv_emp.c",
    "lib/mpv_err.c",
    "lib/mpv_frm.c",
    "lib/mpv_get.c",
    "lib/mpv_hdec.c",
    "lib/mpv_lib.c",
    "lib/mpv_vlc.c",
    "lib/mpv_umc.c",
    "lib/mpv_mcy.c",
    "lib/mpv_m2v.c",
    "lib/mpvabdec.c",
    "lib/memcpyd.c",
    "lib/uty_ppc.c",
    "lib/dct_fsri.c",
    "lib/mpv_bdec.c",
    "lib/mpv_cdec.c",
    "lib/mpv_cmc.c",
    "lib/mpv_dec.c",
    "lib/mpv_mc.c",
    "lib/dct_ac.c",
    "lib/dct_ver.c",
    "lib/adx_insh.c",
    "lib/adx_sfa.c",
    "lib/adx_sje.c",
    "lib/adx_sugc.c",
    "lib/adx_gc.c",
    "lib/mfci.c",
    "lib/gcci.c",
    "lib/gcci_sub.c",
    "lib/eabi.c",
    "lib/crtbegin.c",
    "game/ctrl00.cpp",
    "game/ctrl10.cpp",
    "game/ctype_.c",
    "game/impure.c",
    "lib/builtin-delete.c",
    "game/snd_ram.cpp",
    "lib/pl2link.c",
    "lib/pl2enc.c",
    "lib/adx_dcd3.c",
    "game/sn_malloc.c",
    "lib/cft_common.c",
    "lib/crt0.c",
    "lib/AXComp.c",
    "lib/DSPCode.c",
    "game/foot_shadow_tbl.cpp",
    "lib/tors.c",
    "lib/OSFatal.c",
    "game/sn_buf.c",
    "lib/fileCache.c",
]

# unit -> True once every function and all data in the unit match and the DOL still links
MATCHING = {
    # newlib 1.8.2 libc (SN ProDG build), see include/newlib_stdio.h
    "game/ctype_.c": True,
    "game/impure.c": True,
    "game/errno.c": True,
    "game/locale.c": True,
    "game/exit.c": True,
    "game/math_support.c": True,
    "game/vprintf.c": True,
    "game/vsprintf.c": True,
    "game/printf.c": True,
    "game/fprintf.c": True,
    "game/sprintf.c": True,
    "game/sscanf.c": True,
    "game/fread.c": True,
    "game/refill.c": True,
    "game/ungetc.c": True,
    "game/fflush.c": True,
    "game/fopen.c": True,
    "game/fwalk.c": True,
    "game/makebuf.c": True,
    "game/stdio.c": True,
    "game/closer.c": True,
    "game/fstatr.c": True,
    "game/lseekr.c": True,
    "game/readr.c": True,
    "game/strtoul.c": True,
    "game/strtol.c": True,
    "game/mbtowc_r.c": True,
    "game/strtod2.c": True,
    "game/qsort.c": True,
    "game/vfscanf.c": True,
    "game/vfiprintf.c": True,
    "game/writer.c": True,
    "game/sn_buf.c": True,
    "game/sn_malloc.c": True,
    "game/memset_2.s": True,
    # newlib 1.8.2 libm (fdlibm) compiled as C++ through src/lib/<unit>.cpp wrappers
    "lib/e_pow.c": True,
    "lib/e_sqrt.c": True,
    "lib/s_cos.c": True,
    "lib/ef_pow.c": True,
    "lib/k_cos.c": True,
    "lib/k_sin.c": True,
    "lib/e_atan2.c": True,
    "lib/e_log10.c": True,
    "lib/s_atan.c": True,
    "lib/s_fabs.c": True,
    "lib/s_tan.c": True,
    "lib/ef_acos.c": True,
    "lib/ef_asin.c": True,
    "lib/ef_atan2.c": True,
    "lib/ef_sqrt.c": True,
    "lib/sf_atan.c": True,
    "lib/sf_cos.c": True,
    "lib/sf_fabs.c": True,
    "lib/sf_sin.c": True,
    "lib/sf_tan.c": True,
    "lib/k_tan.c": True,
    "lib/e_log.c": True,
    "lib/e_rem_pio2.c": True,
    "lib/kf_cos.c": True,
    "lib/kf_sin.c": True,
    "lib/kf_tan.c": True,
    "lib/ef_rem_pio2.c": True,
    "lib/k_rem_pio2.c": True,
    "lib/s_floor.c": True,
    "lib/kf_rem_pio2.c": True,
    "lib/sf_floor.c": True,
    "lib/s_scalbn.c": True,
    "lib/sf_scalbn.c": True,
    "lib/s_copysign.c": True,
    "lib/sf_copysign.c": True,
    # gcc 2.95.3 libgcc2 / crt, Metrowerks EABI runtime
    "lib/_ashldi3.c": True,
    "lib/_ashrdi3.c": True,
    "lib/_lshrdi3.c": True,
    "lib/_divdi3.c": True,
    "lib/_moddi3.c": True,
    "lib/_udivdi3.c": True,
    "lib/_umoddi3.c": True,
    "lib/_pure.c": True,
    "lib/_exit.c": True,
    "lib/_eh.c": True,  # functions match; the 16 .bss bytes are the remainders of the dead-stripped runtime's statics (three _register_malloc hook words appended)
    "lib/__main.c": True,
    "lib/tors.c": True,
    "lib/__ppc_eabi_init.c": True,
    "game/t_page.cpp": True,
    "game/t_sc_shot.cpp": True,
    "game/t_log.cpp": True,
    "game/t_prim.cpp": True,
    "game/t_util.cpp": True,
    "game/db_log.cpp": True,
    "game/pl_body.cpp": True,
    "game/db_work.cpp": True,
    "game/yz2code.cpp": True,
    "lib/GXDisplayList.c": True,
    # Dolphin SDK (MWCC 1.2.5n, see configure.py SDK_LIBS)
    "lib/DebuggerDriver.c": True,
    "lib/texPalette.c": True,
    "lib/fileCache.c": True,
    "lib/AmcExi2Stubs.c": True,
    "lib/CARDBios.c": True,
    "lib/CARDBlock.c": True,
    "lib/CARDDir.c": True,
    "lib/CARDCheck.c": True,
    "lib/CARDMount.c": True,
    "lib/CARDFormat.c": True,
    "lib/CARDOpen.c": True,
    "lib/CARDCreate.c": True,
    "lib/CARDRead.c": True,
    "lib/CARDWrite.c": True,
    "lib/CARDDelete.c": True,
    "lib/CARDStat.c": True,
    "lib/CARDNet.c": True,
    "lib/CARDUnlock.c": True,
    "lib/CARDRdwr.c": True,
    "lib/axart.c": True,
    "lib/axartsound.c": True,
    "lib/axartcents.c": True,
    "lib/axartenv.c": True,
    "lib/axartlfo.c": True,
    "lib/axart3d.c": True,
    "lib/axartlpf.c": True,
    "lib/syn.c": True,
    "lib/synctrl.c": True,
    "lib/synenv.c": True,
    "lib/synlfo.c": True,
    "lib/synmix.c": True,
    "lib/synpitch.c": True,
    "lib/synsample.c": True,
    "lib/synvoice.c": True,
    "lib/synwt.c": True,
    "lib/seq.c": True,
    "lib/axfx.c": True,
    "lib/reverb_hi.c": True,
    "lib/chorus.c": True,
    "lib/delay.c": True,
    "lib/reverb_hi_4ch.c": True,
    "lib/mix.c": True,
    "lib/AX.c": True,
    "lib/AXAlloc.c": True,
    "lib/AXAux.c": True,
    "lib/AXCL.c": True,
    "lib/AXOut.c": True,
    "lib/AXSPB.c": True,
    "lib/AXVPB.c": True,
    "lib/AXProf.c": True,
    "lib/AXComp.c": True,
    "lib/DSPCode.c": True,
    "lib/dsp.c": True,
    "lib/dsp_debug.c": True,
    "lib/dsp_task.c": True,
    "lib/vi.c": True,
    "lib/Pad.c": True,
    "lib/Padclamp.c": True,
    "lib/ai.c": True,
    "lib/ar.c": True,
    "lib/arq.c": True,
    "lib/EXIBios.c": True,
    "lib/EXIUart.c": True,
    "lib/SIBios.c": True,
    "lib/SISamplingRate.c": True,
    "lib/db.c": True,
    "lib/dvdlow.c": True,
    "lib/dvdfs.c": True,
    "lib/dvd.c": True,
    "lib/dvdqueue.c": True,
    "lib/dvderror.c": True,
    "lib/dvdidutils.c": True,
    "lib/dvdFatal.c": True,
    "lib/fstload.c": True,
    "lib/GXAttr.c": True,
    "lib/GXGeometry.c": True,
    "lib/GXLight.c": True,
    "lib/GXTexture.c": True,
    "lib/GXBump.c": True,
    "lib/GXTev.c": True,
    "lib/GXPixel.c": True,
    "lib/GXTransform.c": True,
    "lib/GXInit.c": True,
    "lib/GXFifo.c": True,
    "lib/GXMisc.c": True,
    "lib/GXFrameBuf.c": True,
    "lib/GXPerf.c": True,
    "lib/GXDraw.c": True,
    "lib/mtx.c": True,
    "lib/mtxvec.c": True,
    "lib/mtx44.c": True,
    "lib/mtx44vec.c": True,
    "lib/vec.c": True,
    "lib/quat.c": True,
    "lib/psmtx.c": True,
    "lib/OS.c": True,
    "lib/OSAlarm.c": True,
    "lib/OSAlloc.c": True,
    "lib/OSArena.c": True,
    "lib/OSAudioSystem.c": True,
    "lib/OSCache.c": True,
    "lib/OSContext.c": True,
    "lib/OSError.c": True,
    "lib/OSExec.c": True,
    "lib/OSFatal.c": True,
    "lib/OSFont.c": True,
    "lib/OSInterrupt.c": True,
    "lib/OSLink.c": True,
    "lib/OSMemory.c": True,
    "lib/OSMutex.c": True,
    "lib/OSReboot.c": True,
    "lib/OSReset.c": True,
    "lib/OSResetSW.c": True,
    "lib/OSRtc.c": True,
    "lib/OSSemaphore.c": True,
    "lib/OSStopwatch.c": True,
    "lib/OSSync.c": True,
    "lib/OSThread.c": True,
    "lib/OSTime.c": True,
    "lib/PPCArch.c": True,
    "game/strlen.c": True,
    "game/strcpy.c": True,
    "game/strcmp.c": True,
    "game/strncmp.c": True,
    "game/strcat.c": True,
    "game/strncat.c": True,
    "game/strncpy.c": True,
    "game/strchr.c": True,
    "game/strrchr.c": True,
    "game/strstr.c": True,
    "game/strspn.c": True,
    "game/strcspn.c": True,
    "game/strpbrk.c": True,
    "game/memcpy.c": True,
    "game/memset.c": True,
    "game/memcmp.c": True,
    "game/memchr.c": True,
    "game/memmove.c": True,
    "game/isdigit.c": True,
    "game/isspace.c": True,
    "game/tolower.c": True,
    "game/atoi.c": True,
    "game/atof.c": True,
    # light / effect modules
    "game/light_area.cpp": True,
    "game/light04.cpp": True,
    "game/light08.cpp": True,
    "game/light10.cpp": True,
    "game/light03.cpp": True,
    "game/espgen40.cpp": True,
    "game/esp00.cpp": True,
    "game/esp44.cpp": True,
    "game/esp13.cpp": True,
    "game/esp4f.cpp": True,
    "game/esp3f.cpp": True,
    "game/esp40.cpp": True,
    "game/esp41.cpp": True,
    "game/esp42.cpp": True,
    "game/esp4d.cpp": True,
    "game/esp4e.cpp": True,
    "game/espgen01.cpp": True,
    "game/est.cpp": True,
    "game/esp4c.cpp": True,
    "game/esp4b.cpp": True,
    "game/esp4a.cpp": True,
    "game/esp48.cpp": True,
    "game/esp47.cpp": True,
    "game/esp46.cpp": True,
    "game/esp49.cpp": True,
    # esp01-esp1b
    "game/esp05.cpp": True,
    "game/esp0d.cpp": True,
    "game/esp14.cpp": True,
    "game/esp17.cpp": True,
    "game/esp10.cpp": True,
    "game/esp0c.cpp": True,
    "game/esp0b.cpp": True,
    "game/esp07.cpp": True,
    "game/esp06.cpp": True,
    "game/esp1a.cpp": True,
    "game/filter05.cpp": True,
    "game/filter.cpp": True,
    "game/obj06.cpp": True,
    "game/obj04.cpp": True,
    "game/light07.cpp": True,
    "game/light01.cpp": True,
    "game/at_sub2.cpp": True,
    "game/atariInfo.cpp": True,
    "game/atari.cpp": True,
    "game/flr_at.cpp": True,
    "game/se_at.cpp": True,
    "game/cons.cpp": True,
    "game/TmpBuf.cpp": True,
    # misc engine units
    "game/hermite.cpp": True,
    "game/quake.cpp": True,
    "game/tv_mode.cpp": True,
    "game/cString.cpp": True,
    "game/xml.cpp": True,
    "game/room_tex.cpp": True,
    "game/math_sub.cpp": True,
    "game/gx_sub.cpp": True,
    "game/shape.cpp": True,
    "game/geometry.cpp": True,
    "game/file.cpp": True,
    # GX FIFO units (linker-symbol GXWGFifo, see include/gx.h)
    "game/filter03.cpp": True,
    "game/filter01.cpp": True,
    "game/filter04.cpp": True,
    "game/dvd.cpp": False,  # 51/55 functions, all section sizes exact; readMain/Initialize/ErrCheck/DiscChange differ in register allocation only
    # units that mix GQR fast-cast and classic fpmem conversions: need the native v1.79 cc1plus
    # (configure.py --prodg-driver native, the default; see AGENTS.md "Compiler")
    "game/filter0b.cpp": True,
    "game/fade.cpp": True,
    "game/esp01.cpp": True,
    "game/esp19.cpp": True,
    "game/light02.cpp": True,
    "game/light05.cpp": True,
    "game/light06.cpp": True,
    "game/light.cpp": True,
    "game/filter07.cpp": True,
    "game/filter09.cpp": True,
    "game/filter0a.cpp": True,
    "game/filter08.cpp": True,
    "game/filter02.cpp": True,
    "game/filter00.cpp": True,
    "game/esp11.cpp": True,
    "game/esp15.cpp": True,
    "game/esp03.cpp": True,
    "game/esp1b.cpp": True,
    "game/esp43.cpp": True,
}

# C++ units with functions the original linker dead-stripped (bodies gone, constant pools and
# statics kept): tools/strip_unused.py removes the bodies of functions not in sym_map.tsv.
STRIP_UNUSED = {
    "game/puzzle.cpp",
    "game/cam_ctrl.cpp",
    "game/cam_extra.cpp",
    "game/main_mem.cpp",
    "game/sce_at.cpp",
    "game/model.cpp",
    "game/trans.cpp",
    "game/pl_npc.cpp",
    "game/emobj.cpp",
    "game/emrock.cpp",
    "game/shadow.cpp",
    "game/route_ck.cpp",
    "game/cockpit.cpp",
    "game/merchant.cpp",
    "game/light.cpp",
    "game/at_mod.cpp",
    "game/sub2.cpp",
    "game/exception.cpp",
    "game/camera.cpp",
    "game/atariInfo.cpp",
    "game/flr_at.cpp",
    "game/at_sub.cpp",
    "game/motion.cpp",
    "game/obj26.cpp",
    "game/pl_debug.cpp",
    "game/main_sub.cpp",
    "game/filter01.cpp",
    "game/filter09.cpp",
    "game/shape.cpp",
    "game/geometry.cpp",
    "game/obj00.cpp",
    "game/obj15.cpp",
    "game/objGondola.cpp",
    "game/obj12.cpp",
    "game/pl_wep.cpp",
    "game/cam_motion.cpp",
    "game/cam_sys.cpp",
    "game/ctrl01.cpp",
    "game/trans_ot.cpp",
    "game/em_cloth.cpp",
    "game/embox.cpp",
    "game/objWep.cpp",
    "game/cloth.cpp",
    "game/esp_app.cpp",
    "game/map_obj.cpp",
    "game/Espgen43.cpp",
    "game/Espgen42.cpp",
    "game/espgen45.cpp",
    "game/esp43.cpp",
    "game/emtree.cpp",
    "game/objRobo.cpp",
    "game/atari.cpp",
    "game/pendulum.cpp",
    "game/em_sub.cpp",
    "game/player.cpp",
    "game/obj03.cpp",
    "game/obj02.cpp",
    "game/scroll.cpp",
    "game/view.cpp",
}

# Capcom sound library (game/snd_*.cpp): C++ with extern "C" functions, compiled unoptimised
# (frame pointer in r31, every local in a stack slot, dead jumps kept).
SND_UNITS = [
    "game/snd_ram.cpp", "game/snd_main.cpp", "game/snd_efx.cpp", "game/snd_iss0.cpp",
    "game/snd_iss1.cpp", "game/snd_iss2.cpp", "game/snd_iss3.cpp", "game/snd_iss4.cpp",
    "game/snd_seq0.cpp", "game/snd_seq1.cpp", "game/snd_seq2.cpp", "game/snd_seq3.cpp",
    "game/snd_str0.cpp", "game/snd_str1.cpp", "game/snd_str2.cpp", "game/snd_str3.cpp",
    "game/snd_str4.cpp", "game/snd_sub0.cpp", "game/snd_sub1.cpp", "game/snd_sub2.cpp",
    "game/snd_sub3.cpp",
]
UNIT_CFLAG_OVERRIDES = {u: {"-O2": "-O0"} for u in SND_UNITS}
MATCHING.update({
    "game/snd_ram.cpp": True,
    "game/snd_main.cpp": True,
    "game/snd_iss0.cpp": True,
    "game/snd_sub0.cpp": True,
    "game/snd_sub1.cpp": True,
    "game/snd_sub2.cpp": True,
    "game/snd_sub3.cpp": True,
    "game/snd_iss1.cpp": True,
    "game/snd_efx.cpp": True,
    "game/snd_seq0.cpp": True,
    "game/snd_seq1.cpp": True,
    "game/snd_seq2.cpp": True,
    "game/snd_seq3.cpp": True,
    "game/snd_str0.cpp": True,
    "game/snd_str1.cpp": True,
    "game/snd_str2.cpp": True,
    "game/snd_str3.cpp": True,
    "game/snd_str4.cpp": True,
    "game/snd_iss2.cpp": True,
    "game/snd_iss3.cpp": True,
    "game/snd_iss4.cpp": True,
})

# player units (game/pl_*.cpp, debug, read)
MATCHING.update({
    "game/pl_event.cpp": True,
    "game/pl_knife.cpp": True,
    "game/pl_ashley.cpp": True,
    "game/pl_leon.cpp": True,
    "game/pl_push.cpp": True,
    "game/pl_cloth.cpp": True,
    "game/pl_dmg.cpp": True,
    "game/player.cpp": True,
    "game/path.cpp": True,
    "game/TexRender.cpp": True,
})

# map object units (game/obj*.cpp)
MATCHING.update({
    "game/obj01.cpp": True,
    "game/obj10.cpp": True,
    "game/obj15.cpp": True,
    "game/obj16.cpp": True,
    "game/objGondola.cpp": True,
    "game/obj19.cpp": True,
    "game/obj20.cpp": True,
    "game/obj26.cpp": True,
    "game/obj14.cpp": True,
    "game/obj1c.cpp": True,
    "game/obj08.cpp": True,
    "game/obj1d.cpp": True,
    "game/obj18.cpp": True,
    "game/obj.cpp": True,
    "game/map_obj.cpp": True,
    "game/obj05.cpp": True,
    "game/objRocket.cpp": True,
    "game/objSubWep.cpp": True,
    "game/objBull.cpp": True,
    "game/obj13.cpp": True,
})

# media/utility units
MATCHING.update({
    "game/cDataSwap.cpp": True,
    "game/cinesco.cpp": True,
    "game/sofdec.cpp": True,
    "game/yz2asm.s": True,
    "game/scheduler.cpp": True,
    "game/libgpu.cpp": True,
})

# enemy units (game/em*.cpp, et00)
MATCHING.update({
    "game/emdata.cpp": True,
    "game/em_dm_val.cpp": True,
    "game/et00.cpp": True,
    "game/emhit.cpp": True,
    "game/emtorch.cpp": True,
    "game/emitem.cpp": True,
    "game/em.cpp": True,
    "game/emrack.cpp": True,
    "game/emtree.cpp": True,
})

# area / message units
MATCHING.update({
    "game/area.cpp": True,
})

# camera units
MATCHING.update({
    "game/cam_sys.cpp": True,
    "game/cam_motion.cpp": True,
    "game/camera.cpp": True,
})

# control (ctrl*) units
MATCHING.update({
    "game/ctrl00.cpp": True,
    "game/ctrl01.cpp": True,
    "game/ctrl10.cpp": True,
    "game/ctrl11.cpp": True,
    "game/ctrl12.cpp": True,
    "game/ctrl14.cpp": True,
    "game/ctrl.cpp": True,
})

# transfer units (lighting, ordering table)
MATCHING.update({
    "game/trans.cpp": True,
    "game/trans_lit.cpp": True,
    "game/trans_ot.cpp": True,
})

# collision / model helper units (atari, cloth, ik, mirror, pendulum ...)
MATCHING.update({
    "game/mirror.cpp": True,
    "game/cloth.cpp": True,
    "game/ik.cpp": True,
    "game/block.cpp": True,
    "game/foot_shadow.cpp": True,
    "game/foot_shadow_tbl.cpp": True,
})

# system / UI units
MATCHING.update({
    "game/main.cpp": True,
    "game/sub2.cpp": True,
    "game/dmg.cpp": True,
})

# effect system units
MATCHING.update({
    "game/eff_sys.cpp": True,
    "game/espgen.cpp": True,
    "game/espgen00.cpp": True,
})

MATCHING.update({
    "game/cockpit.cpp": True,
})

MATCHING.update({
    "game/obj09.cpp": True,
})

MATCHING.update({
    "game/emwindow.cpp": True,
})

# object units whose cAtariInfo::init argument order needed atari_init.h
MATCHING.update({
    "game/objTrolley.cpp": True,
    "game/objYagura.cpp": True,
    "game/objMissile.cpp": True,
    "game/emswitch.cpp": True,
    "game/embarrel.cpp": True,
})

MATCHING.update({
    "game/item_model.cpp": True,
})

MATCHING.update({
    "game/cMotBase.cpp": True,
})

# game task: cGameSave shared-temp fixups, GamePointInit/GameAddPoint switch shapes, fadeSetG
MATCHING.update({
    "game/game.cpp": True,
})


MATCHING.update({
    "game/lightInfo.cpp": True,
})

# closer: plain-block HALT (li r4,0 before the string in DLL_Link/DLL_Unlink), lbl_ names for the
# two unreferenced .sdata ints, chained/zero store orders
MATCHING.update({
    "game/main_sub.cpp": True,
})

# esp closer: sprite corner idiom in Shimmer/Nega, EspSeqSet real parameter order (f32 before out)
MATCHING.update({
    "game/esp_sub.cpp": True,
    "game/esp0f.cpp": True,
    "game/espgen44.cpp": True,  # Filter05SetParam per-call-site argument-order aliases
})

# enemy closer: ckObj's `&EmMgr` hoist (block-scoped manager pointer + two-statement work address)
MATCHING.update({
    "game/emdoor.cpp": True,
})

# enemy closer: setYarare narrow re-extension (int copies laundered through empty asms, flag pinned to
# r6), SatMgrCreateF floats-first alias, dead pool-only static (STRIP_UNUSED)
MATCHING.update({
    "game/emobj.cpp": True,
})

# enemy closer: emBoxDmCk's second switch lays its SetBreak(0) arms out before the 7/8/0x21 if/else
MATCHING.update({
    "game/embox.cpp": True,
})

# enemy closer: id_tex (IdTexSet's laundered u8 argument, IdTexDataLoad's integer table base)
MATCHING.update({
    "game/id_tex.cpp": True,
})

# UI/system closer (stage)
MATCHING.update({
    "game/stage.cpp": True,
})

# CRI Middleware libraries (ADX / Sofdec / GCCI, CodeWarrior 2.4.7 -O4,p, see configure.py CRI_LIBS)
MATCHING.update({
    "lib/adx_fcch.c": True,
    "lib/adx_gc.c": True,
    "lib/sj_err.c": True,
    "lib/lsc_crs.c": True,
    "lib/rna_crs.c": True,
    "lib/adx_crs.c": True,
    "lib/mcp_not.c": True,
    "lib/sj_crs.c": True,
    "lib/mps_del.c": True,
    "lib/adx_bahx.c": True,
    "lib/sfx_inf.c": True,
    "lib/mwsfdrsc.c": True,
    "lib/mwsfdsee.c": True,
    "lib/memcpyd.c": True,
    "lib/memsetd.c": True,
    "lib/cmptime.c": True,
    "lib/muldiv.c": True,
    "lib/uty_ppc.c": True,
    "lib/lsc_err.c": True,
    "lib/rna_err.c": True,
    "lib/sfd_tmr.c": True,
    "lib/adx_sfa.c": True,
    "lib/mpv_m2v.c": True,
    "lib/adx_fsvr.c": True,
    "lib/sfx_sud.c": True,
    "lib/mwsfdrna.c": True,
    "lib/dct_ver.c": True,
    "lib/gcci_sub.c": True,
    "lib/uty_tmr.c": True,
    "lib/sfd_mem.c": True,
    "lib/sfx_set.c": True,
    "lib/adx_sugc.c": True,
    "lib/pl2enc.c": True,
    "lib/pl2link.c": True,
    "lib/cft_common.c": True,
    "lib/adx_dcd3.c": True,
    "lib/mpv_err.c": True,
    "lib/lsc_ini.c": True,
    "lib/adx_insh.c": True,
    "lib/sud_lib.c": True,
    "lib/mwstm.c": True,
    "lib/mwsfdsl.c": True,
    "lib/sfx_cnv_to_Y84C44.c": True,
    "lib/sfx_cnv_to_ARGB8888PLN.c": True,
    "lib/mwsfx_Y84C44.c": True,
    "lib/mwsfx_ARGB8888PLN.c": True,
    "lib/mpv_get.c": True,
    "lib/dummy.c": True,
    "lib/sfd_vom.c": True,
    "lib/mps_get.c": True,
    "lib/adx_rnaa.c": True,
    "lib/adx_amp.c": True,
    "lib/adx_mgc.c": True,
    "lib/sj_mem.c": True,
    "lib/sj_uni.c": True,
    "lib/adx_fini.c": True,
    "lib/sj_utl.c": True,
    "lib/adx_inis.c": True,
    "lib/adx_errs.c": True,
    "lib/adx_xpnd.c": True,
    "lib/muldivr.c": True,
    "lib/mpv_deli.c": True,
    "lib/sfd_con.c": True,
    "lib/sfd_pl2.c": True,
    "lib/sfd_trn.c": True,
    "lib/lsc_svr.c": True,
    "lib/mwsfdsvm.c": True,
    "lib/sfx_YCC420PLN_to_Y84C44.c": True,
    "lib/mpv_bdec.c": True,
    "lib/sfx_lib.c": True,
    "lib/mwsfdlib.c": True,
    "lib/sfd_aoap.c": True,
    "lib/adx_bsps.c": True,
    "lib/mwsfdsst.c": True,
    "lib/mwsfdset.c": True,
    "lib/adx_fs.c": True,
    "lib/sfd_mpvf.c": True,
    "lib/mpv_emp.c": True,
    "lib/sj_rbf.c": True,
    "lib/mpv_lib.c": True,
    "lib/sfx_YCC420PLN_to_ARGB8888PLN.c": True,
    "lib/mpv_mc.c": False,  # CRI SWAR kernels pass 2: asm bodies replaced by pure C except OneRef1p (lfdux/lwzux: asm in the original); 4p 72w (count/stride r0 swap + loop registers), H2 436w (masks hoisted with opt_propagation off; the target's un-split loop variables), V2 73w (case 0 identical: average through mask variables + declaration order x0, w0, a0, x1, w1, a1; cases 1-3 register/mr residue), 1p 481w (the original's lfdux/lwzux update forms are not emitted from C by this compiler)
})

# partner character (pl_npc): const f32 locals for pool order, per-value switch bodies, dead
# `farCheck` inline whose pool word survives the strip (STRIP_UNUSED)
MATCHING.update({
    "game/pl_npc.cpp": True,
})

# SN libsn FSasync: volatile transfer state (reloads), `for (;;) { cnt--; if (cnt == -1) break; }`
# loops (shared @ha register), 32-byte aligned DMA result struct, -fno-common .bss order
MATCHING.update({
    "lib/FSasync.c": True,
})

# SN libsn sndvd: DABR set through an "m" asm operand (stack slot + hard r3), DSIExcHandler as one
# top-level asm block, uncached DI address `(0x0C006000 + i*4) | 0xC0000000` inside the copy loop,
# empty asm keeping the default case's `bl ForceDvdDeIrq` from being cross-jumped (COMPILER-DIFF #6)
MATCHING.update({
    "lib/sndvd.c": True,
})

# AX FX standard reverb: `max_length << 2` in DLcreate decides `rv`'s callee-saved register
MATCHING.update({
    "lib/reverb_std.c": True,
})

# CRI SVM server manager: volatile lock/init counters (reloads), inlined svm_exec_svr helper (zero
# copies), dead setters/getters for the first-reference .bss order, `*p++ = 0` unrolled clear
MATCHING.update({
    "lib/svm.c": True,
})

# CRI AX renderer: inlined public setters/getters, `sw` flag byte with |=/&= masks, separate
# loop/cur locals for the AXPBADDR fill, inlined axrna_exec_trans/axrna_exec_flash helpers
MATCHING.update({
    "lib/ax_rna.c": True,
})

# hand-written libsn/crt assembly (src/lib/*.s, see configure.py ASM_UNITS): local branch targets
# are resolved by the assembler, so objdiff shows ARG_MISMATCH on them; the linked bytes are identical
MATCHING.update({
    "lib/proview.c": True,
    "lib/ppcdown.c": True,
    "lib/fileserver.c": True,
    "lib/eabi.c": True,
    "lib/__start.c": True,
    "lib/tealeaf.c": True,
})

# item examine: single-assignment float locals for the camera setup (dist/r/y/z each die once, so
# local-alloc orders the FPRs by refs/length), `-y` stores with target.y first
MATCHING.update({
    "game/examine.cpp": True,
})

# misc object units: dead-stripped out-of-line inits whose pools survive (obj03 init), .sdata pads
MATCHING.update({
    "game/obj03.cpp": True,
    "game/obj02.cpp": True,
    "game/obj12.cpp": True,
    "game/objPillar.cpp": True,
})

# system units: file_lock reads pUser_name directly in each arm (a `path =` reassignment gives a
# phantom r31 save); pl_sub: `cPlayer* pl = pPL` before a switch, `goto` to a shared `return 0`,
# `const f32` limit across a call, guarded do/while list walks testing `next`
MATCHING.update({
    "game/file_app.cpp": True,
    "game/pl_sub.cpp": True,
})

# EtcModel: GetEtcAmbType's first `return 1` copy kept with an empty `asm volatile("")` opening the
# else arm (COMPILER-DIFF 6, see the source comment)
MATCHING.update({
    "game/EtcModel.cpp": True,
})

# eprintf: `dst = mess_keep_ptr` read inside the slot-search loop with a single early return (gcse PRE
# copy instead of cse), loop test through a cast so the table pointer is reloaded per iteration,
# `s16 x = lo; x |= hi << 8` byte assembly, s16 coordinate copies declared after GXBegin
MATCHING.update({
    "game/eprintf.cpp": True,
})

# scroll: index-first integer table address in SmdClear (the store aliases the scalar table pointer),
# format strings in `const char*` locals so jump.c does not hoist the early `return NULL`s, `goto ok`
# around the shared NULL return, do/while list walk testing `next`, `u32 base` for the bin table,
# `nTpl = 0` before the getWorkPtr call; SmdGetIdNumPtr is dead-stripped (STRIP_UNUSED)
MATCHING.update({
    "game/scroll.cpp": True,
})

# at_sub: the sphere/capsule end-point distances through one twice-set `d` (no tie to the dz chain),
# At_poly_sphere_ck2's `hit = 99` after the fabsf asm, `hit = 0` inside the surface-hit arm and the
# rim-hit arm's `goto hit1` into the surface-hit `hit = 1` (the original cross-jump survivor)
MATCHING.update({
    "game/at_sub.cpp": True,
})

# mpv_vlc (CRI Sofdec VLC tables): `-inline auto,deferred` (CRI_CFLAG_OVERRIDES) — .text is the
# reverse of the source order and .bss is laid out in *reverse declaration order* (no first-reference
# placement under deferred), .rodata stays in declaration order; table fills are `for (i < n) *p++`
# loops (<= 8 iterations unrolled without guard, 9..32 with the `li 0; cmpwi n; bge` guard, more as
# 32-store mtctr loops); per-code-length groups are blocks with their own `k/i/v` (a shared `k`
# chains consecutive one-iteration loops); `Sint16 v` fills give the `extsh` of 16-loops (I tables,
# motion) while the P/B tables store the expression directly; the VLC area layout keeps the
# run/level start in a copy (`rl = p`) and derives the lower tables from it (r18 base)
MATCHING.update({
    "lib/mpv_vlc.c": True,
})

# adx_tlk (CRI ADXT handle API): `-inline auto,deferred` (CRI_CFLAG_OVERRIDES) — .text is the reverse
# of the source, the public accessors are inlined into SetOutputMono/GetTime/DiscardSmpl/StartSj,
# the dead-stripped API functions are kept for their strings (codegen order), .bss reverse declaration
MATCHING.update({
    "lib/adx_tlk.c": True,
})

# DOL register/cross-jump tie pass (2026-09-10): the `||` return-0 test written as `goto ng` so no
# label precedes the surviving `return 1` (pl_class isKamae); a `do {} while (0)` around the last
# `pCur` store doubles that `this` ref's global-alloc weight (lightPath movePath: this r9, pCur r11)
MATCHING.update({
    "game/pl_class.cpp": True,
    "game/lightPath.cpp": True,
    "game/rnd.cpp": True,  # `m = (n << 16) >> 16` keeps m out of n's cse class (the `mr r0,r9` copy)
    "game/emBar.cpp": True,  # do-while around emBarSetBreak: 7th weighted em ref (em r31, p r30)
    "game/vfprintf.c": True,  # fftoa: do-while notes around `u.d = value` and the lo/hi word reads
})

# DOL register-tie pass, second sweep (2026-09-10)
MATCHING.update({
    "game/datactrl.cpp": True,  # dispDebug: one function-scope x1 shared with the over block (conflict union -> r5)
    "game/read.cpp": True,  # readEmData: do-while around the dll else arm (m 15 weighted refs > newSize)
})

# DOL sweep 4, one-function units (2026-09-10)
MATCHING.update({
    "game/esp.cpp": True,  # operator new: loop3 as a `for` (cse_around_loop copy) with a do-while(0) around `PushEsp; goto found`
    "game/esp_efm.cpp": True,  # EfmSetObj04: parent/parentSerial stored through a u32* (register-address store invalidates x79 in cse1)
})

# DOL sweep 5, one-function units (2026-09-10)
MATCHING.update({
    "game/room_jmp.cpp": True,  # roomJumpMove: nested s8 ternary through an s8& setter (QI temp -> jump1 hoists the 0 -> conflicts with r3)
})

# CRI one-function-away pass (2026-09-10)
MATCHING.update({
    "lib/cftcoladj.c": True,  # `cbtbl[i] = i * v / j` (the i*v product is MWCC's strength-reduced IV, not a source local); last ramp loops on v with the start copied
    "lib/lsc.c": True,  # EntryFileRange: raw previous id read first, then ent = GetWrEntry, then the wrap ternary (temporaries in place)
})

# DOL sweep 7, one-function units (2026-09-10)
MATCHING.update({
    "game/emBarred.cpp": True,  # SetEmBarred: `em->hpMax = em->hp = 1000` repeated in every YarareInitCube arm so case 4 does not end in the call (flow `use 0` nop) and all arms cross-jump into its tail
})

# DOL sweep 8 (2026-09-10)
MATCHING.update({
    "game/espgen10.cpp": True,  # EspgenDataSet: EspEvModList high/low as pinned r9/r11 asm insns + pinned r9 index (#13: REG_EQUIV high and mem never allocated in the original)
})

# DOL sweep 9 (2026-09-10)
MATCHING.update({
    "game/obj1b.cpp": True,  # obj1bHitCk: `no = partsNo ? partsNo - 1 : 0` ends cse's ebb at the select's join, so the later `&obj->pos` occurrences are PRE'd into the post-getPartsPtr copy
})

# DOL sweep 10 (2026-09-10)
MATCHING.update({
    "game/texture.cpp": True,  # DataLoad: ofsId/ofsTpl temporaries pinned to r9/r11 (local-alloc fake-lifetime tie; same schedule)
})

# DOL sweep 11 (2026-09-10)
MATCHING.update({
    "game/merchant.cpp": True,  # sellPrice: the bullet PriceEntry reuses `p` (2-set pseudo: no birthing boost on the `mr.`, so sched1 puts it after the two pool `lis` and local-alloc gives the highs r11/r10)
})
MATCHING.update({
    "game/snd.cpp": True,  # SndCall RefU32 flags read (param stores rank above lwz pG), SndSetReverb one `p` for both arms, SndRoomBgmStart nested do-while weights, sndVolCalcSub dead `dist > vol` test (r -> f2)
})
MATCHING.update({
    "game/pl_debug.cpp": True,  # DrawGage: opaque `fadds len,fx,len` (expand_binop puts the destination operand first; tagged candidate)
})

# COMPILER-DIFF #8 pass (2026-09-10)
MATCHING.update({
    "game/emshield.cpp": True,  # setFall: DFmode `register f64 asm("fr1")` read in a "=m" asm keeps f1 live past the parameter copy (#8: the copy ranks as weight +1)
})
MATCHING.update({
    "game/t_flag.cpp": True,  # move: `cur & 0xF` pinned to r11 (untied add) and `cur >> 6` pinned to r0 (#17)
})
MATCHING.update({
    "game/objWep.cpp": True,  # drawPoint: first `esp` reload pinned to r11 (#17)
})
MATCHING.update({
    "game/filter06.cpp": True,  # cParticle06::move: alphaBase pinned to r11 (#17)
})

# CRI pass 3 (2026-09-10)
MATCHING.update({
    "lib/adx_bwav.c": True,  # ADX_DecodeInfoWav: dsize swap before *hdrlen/*x0c (the -1 is stored mid-chain, so the chain lands in r3 and is copied), `4 + i + (Sint32)buf` keeps add/lwz 4()
    "lib/sfd_lib.c": True,  # SFD_Init: the two SFD_INIT_PRM word loads as `asm { lwz p1, 4(prm) }` / `asm { lwz tbl, 0(prm) }` on register locals (COMPILER-DIFF: M1, word 4 loaded first)
    "lib/sfd_uo.c": True,  # SFUO_Create: channel clear in an inlined static helper called with `&sfd->uo_tbl` (zero-copy `i = 0`, the argument itself is the stepping pointer)
})
MATCHING.update({
    "game/espgen02.cpp": True,  # espgen02_Update: colR pinned to f24, copies between the bScale/bSpd zero stores (#17)
})

# DOL sweep 12 (2026-09-10)
MATCHING.update({
    "game/event.cpp": True,  # DelEvt: FadeSetW written out (`u32* c`, `c[1]` keeps P tied to r4), `int zero; zero = 0;` set before `if (fade)` (#13 single-use zero, update_equiv_regs moves the li to the store -> r0)
    "game/esp45.cpp": True,  # Esp45_HideCheck: dead `if (w->flags == 99) ox = oy;` at the loop body end (+3 real insns: high(Screen) misses loop pass 1's threshold and is hoisted in pass 2, after the giv init)
    "game/exception.cpp": True,  # ErrorHandler: 15 dead `f32 lcN = K;` pool constants shift the string labels to .LC79/.LC80 so the gcse PRE pseudo order (hash-bucket) gives DSISR r16 / symbol_err_tbl r15 / CALL STACK r14
    "game/esp_app.cpp": True,  # EspDrawLaserLine: 0.8f as a named .rodata word + asm lis/lfs with hi pinned r11 and `li r8,5` asm-chained (#13); EffAreaUpdate: codeless "=m" asm as a sched2 issue-slot filler
})

# CRI pass 4 (2026-09-10)
MATCHING.update({
    "lib/sfd_ply.c": True,  # SFD_Destroy returns SFTRN_CallTrSetup's result (r3 live across the hn-table clear -> loop r4/r5, sfd r31)
    "lib/sfd_set.c": True,  # SFD_SetCond: id*4 as an asm-defined `register` local (takes the dead sfd register r28), hn declared first (COMPILER-DIFF: M1)
    "lib/mps_dec.c": True,  # mpsdec_DecPackHd: reader init written out (`cur = p[0]; ... cur <<= pos;`), locals declared p, pos, cur, nxt
})

# CRI pass 5 (2026-09-10)
MATCHING.update({
    "lib/rna_res.c": True,  # RNARES_Init: the hoisted 0x1000 and ptr+ofs named as asm-defined `register` locals -> volatiles in declaration order ofs, half, sum, ptr, res (COMPILER-DIFF: M1)
    "lib/mfci.c": True,  # mfCiReqRd: asm-defined `register` copy of the mfci parameter (coalesced into the prologue mr.) ranks it r29 above buf r28 (COMPILER-DIFF: M1)
    "lib/mpv_frm.c": True,  # MPV_SkipFrmSj/MPV_DecodeFrmSj: asm-defined `register` copy of hn ranks mpv r31 above the other parameters and locals (COMPILER-DIFF: M1)
})

# CRI pass 6 (2026-09-10)
MATCHING.update({
    "lib/adx_sjd.c": True,  # adxsjd_decode_prep: `asm { lwz r5, ck.len; mr len, r5 }` pins the post-call single-use length to r5 (hard-register asm pin, COMPILER-DIFF: M1)
    "lib/adx_dcd.c": True,  # ADX_GetCoefficient: `#pragma pool_data off` before the function (COMPILER-DIFF: M2 - the original does not count the function's own float literals towards the pool threshold; CRI pass 9)
    "lib/dct_ac.c": False,  # CRI pass 8 (pure-C revert): DCT_AcInit 37w (M2: pooled literals + `...bss.0` base for dctac_version_dummy, one more callee-saved register)
    "lib/sfd_see.c": True,  # SFSEE_ExecServer: hard-register asm pins for the inlined wk/req (r29/r30) and the CalcByteRate wk reload (r29) (COMPILER-DIFF: M1)
    "lib/sfd_pts.c": True,  # SFPTS_ReadPtsQue: eight hard-register asm pins (hn/-1 r7, rd r12, idx r4, st r3, cnt-i r3, &ent[idx] r3) (COMPILER-DIFF: M1)
    "lib/mwsfdply.c": True,  # MWSFPLY_SetFlowLimit: MWSFD_SetFlowLimit(mwply, 0.8 * n, n) takes a third argument (CRI pass 9 replaced the r5 pin, which was a missed parameter)
    "lib/sfx_alp.c": True,  # SFXA_Create: constants, the sfxa_work address and the r0 temporaries (also the inlined search's) pinned with hard-register asm (COMPILER-DIFF: M1)
    "lib/mwsfdsfx.c": True,  # CnvFrmInfToSfx: parameter pins r27/r30/r31 + plane-1 loads as asm-defined register locals (COMPILER-DIFF: M1); tag strings named and declared before mwsftag_GetAinfFromSj for the .rodata order (COMPILER-DIFF: M3)
    "lib/adx_bau.c": True,  # CRI pass 10: ADXB_ExecOneAu16 2ch swap through a `Uint16 x` temporary `(x << 8) | (x >> 8)` gives the unroller's 15th copy as `extrwi` (the "M6" was a source shape)
    "lib/adx_stmc.c": True,  # CRI pass 10: adxstmf_create's search as `(Uint8 *)adxstmf_obj + ofst * sizeof(ADXSTM_OBJ)` with `ofst++` after the test (scaled-index IV stepped in the latch)
    "lib/mpv_cdec.c": True,  # MPVCDEC_IntraBlocks: the six blocks cleared by six calls of a static inline helper storing 32 doubles through a `Float64 **cur` cursor (the second clear base `addi r8, mpv, 0x720` follows; CRI pass 9, shape from mk-deception)
    "lib/sfd_cre.c": False,  # CRI pass 14: sfcre_AnalyMpv 15w (the `ofs + 1` backend temp is coloured after the b4/b7 byte variables in the target, r0, before them in ours, r4 in place of ofs) / AnalyAudio 43w / AnalyMps 28w (inlined-helper temporaries and callee-saved permutations)
    "lib/cri_cvfs.c": False,  # CRI pass 13: 11/13, cvFsGetFileSize 63w / cvFsOpen 240w (-4 bytes) (the inlined cvfs_ResolveDev: pdev above tbl, tbl materialised after strlen); cvFsAddDev fixed by kept devname/getif copies + the inlined cvfs_AddDevTbl helper
    "lib/adx_baif.c": False,  # CRI pass 10: 5/6, AIFF_GetInfo 91w (M1: FORM/size words share the loop registers); ExecOneAiff16 fixed by the `Uint16` swap temporary
    "lib/adx_dcd5.c": False,  # CRI pass 9: ADX_DecodeSte4AsSte 118w / Ste4AsMono 167w / Mono4 39w (M1 register ranking only: the original keeps smul in r0 / i in r10 / c1,c2 extended in place; the history locals declared first fixed the AdxQtbl address hoist)
    "lib/mwsfdsvr.c": True,  # CRI pass 12: `void *obj` handlers with a kept MWPLY copy, function-scope sfd, the sleep loop as an inlined helper
    "lib/sfd_tst.c": False,  # CRI pass 14: 10/11, SFTST_Calc 79w (the abs diamond anchored above the sftst_Conv call by the nested `diff =` assignment; residue = diff pair lo/hi ranking r23/r25 vs r25/r23: the backend propagates `mr diff, sub` so the pair are backend temps above adiff.hi); .rodata order kept by the named strings
    "lib/sfx_zmv.c": False,  # CRI pass 8 (pure-C revert): sfxzmv_MakeCnvZTbl 94w (M1: inlined helper src/dst r3/r4) / MakeOrgZ32TblByCCIR 77w (M1: unrolled 1.164f loop slot order)
})

# DOL structural pass (2026-09-10)
MATCHING.update({
    "game/dbmodule.cpp": True,  # DrawObjWireframe: do{..}while(1) command loop (no rotation), ISet(DB_poly_num), `*pidx++ =` idx stores, `idx[2] = idx[1]; pidx = &idx[1];`, one `s16* v`, own `u32 m2` for the strip emit loop
})

# DOL sweep 13 (2026-09-10)
MATCHING.update({
    "game/esp0e.cpp": True,  # Esp0e_Trans: plain polymorphic `*p = *esp` (pure C since the shipped-build-temp-flags compiler patch, 2026-09-11); stores `id, pModel, partsNo, life`
    "game/pad.cpp": True,  # PadRead: `register int dead asm("r16")` set by a volatile asm `li` (#17/#13): the hoist keeps r17, the li is the block's first insn
})

# CRI pass 7 (2026-09-10)
MATCHING.update({
    "lib/mpv_dec.c": True,  # MPVDEC_END: ck.data as an asm-defined `register` local so q stays in r4 and the load takes r8 (COMPILER-DIFF: M1); `(Uint8)val` skip lengths (zero-code)
})

# DOL sweep 15 (2026-09-11)
MATCHING.update({
    "game/model.cpp": True,  # drawBoundingBox: counted `for (j < 8) PSVECAdd(&v[j], ..)` loop (giv init after the gcse insertions, biv-eliminated `cmplw; ble`) instead of the do-while pointer loop; zero code
    "game/esp16.cpp": True,  # Esp16_Trans: dead three-load test after the 0.0 load splits the block at sched (COMPILER-DIFF candidate, sched block split) + the #13 fr12 pin; keep-alive asm dropped
})

# DOL structural pass 2 (2026-09-11)
MATCHING.update({
    "game/item.cpp": True,  # set_stage2: LV_SET macro sets the EX nibble first (the all-zero mask chain then folds in combine, whose dead loads leave the USE insns that make `mr r3,this` the loop-note barrier); init: `li r3,32` as an asm-li with a dying input (#13); trigger: r9 pin + launder for the u16 mask (#2)
})

# CRI pass 9 (2026-09-11): shapes verified against mk-deception's copy of the same CRI libraries
MATCHING.update({
    "lib/dct_fsri.c": True,  # DCT_FsriTransCore: the paired-single kernel's FPRs (c1..c6 constants, 9 temporaries) and the B0TableOrg pointer as `register __vec2x32float__`/pointer variables instead of hard registers (the C paths then share f0/f7 and r5/r7; cnt declared before o); dctfsri_Idx static inline with `int`s, initSparseTbl under `#pragma opt_loop_invariants off` storing through an inline `const Float64 *` helper; B0TableOrg[0] = sqrt(2)
    "lib/mpvabdec.c": True,  # two-word bit reader written out per case (`bitpos += n` before the coefficient stores, refill after); the non-intra first coefficient / skip / AC loop as three static inline helpers under `#pragma inline_max_size`; the escape look-ahead through a fresh `mpvabdec_EscapeCode()` value in NintraBlock/Dc11 and in place in IntraBlock; run/level tables read as `const Sint16 *`
})

# CRI pass 10 (2026-09-11): declaration-order shapes
MATCHING.update({
    "lib/mwsfdfrm.c": True,  # mwl_convFrmInfFromSFD: the ten frame-field copies declared LAST rank r31..r22 above the parameters; pptr declared before usrlen/usrptr (zero code, no pins)
})

# DOL sweep 15b (2026-09-11)
MATCHING.update({
    "game/sscrn.cpp": True,  # SubScreenExit: `u32 clear = 0` before cMes.roomInit() feeds a local FadeSetBlackOut inline (the zero stays a loop-body pseudo, not combined with the `type`/`flags` zero and hoisted), `type = 0; flags = 0` separate, BitSet/BitOff reference stores, `area_no != -1` polarity; OpeSetOpenTerm: codeless asm past z's death (tie, x 216 -> 217); the 12-byte .text pad is lib/ppcdown.s's `.balign 32`
    "game/esp0a.cpp": True,  # Esp0a_Trans/SetFreeWork: the four polymorphic `*p = *q` copies written plainly (pure C since the shipped-build-temp-flags compiler patch, 2026-09-11), `colRSpd..scaleCnt` as separate statements (a reload of e.p per store), `int ot = 8` local before the parent test (callee-saved r29 across PSMTXMultVec), pEffParentWorld read through an inline reference
    "game/mes.cpp": True,  # Message::move/WidthCk: a codeless asm between `code = getCharCode()` and its `== 0` test (input-only use in move, `+r` launder in WidthCk) stops combine from fusing the call-result copy and the compare into `mr.` (COMPILER-DIFF candidate)
    "lib/crt0.c": True,  # data-only libsn crt0 half: the two 32-byte message buffers, the version words, `LinkFiddle = {__mod2i, 0}` (the code is lib/__start.s)
    "lib/crtbegin.c": True,  # .ctor/.dtor -1 list heads (`__CTOR_LIST__`/`__DTOR_LIST__` with section attributes)
})

# DOL sweep 16b (2026-09-11)
MATCHING.update({
    "game/esp04.cpp": True,  # move10: y-loop step pinned to fr0 (#17) + a "=m" keep-alive of y after the loop (#13): the `v = y` copy is issued after the hoisted step/bound copies and the loop bound cannot take y's f12
    "game/esp12.cpp": True,  # Esp12_Trans: `u32 magic = 0x43300000` in the CommonStateSet block + a "=m" keep-alive after GXBegin (#13: the conversion constant is a 3-ref callee-saved pseudo hoisted to the block top), the Esp16_Trans zero recipe (fr12 pin + dead three-load test), nrm zero stores as three statements, `r*sizeY + (1-r)*sizeX`, `t += tstep` between the two vertices
    "game/esp02.cpp": True,  # esp02Trans_sub: `&d` in the calls and the inlined VECNormalize (no `pd` copy: one fp+232 pseudo, spilled, its uses rewritten frame-direct), `org.x/y/z = 0.0f` as three statements, `nz = 1.0f - nz` in place, `u32 i` (unsigned `addic.; beq` exit); zero code
})

# DOL sweep 16a (2026-09-11)
MATCHING.update({
    "game/obj00.cpp": True,  # FallMove: codeless call-crossing `junk` pseudo (asm def before the hit loop, "=m" use in the fallSpd loop) ranks between `end` and the hoisted `sePlayed = 1` constant and takes r24, so the constant gets r23 (candidate #17); four dead `i = K` sets keep the gcse bucket count
    "game/t_option.cpp": True,  # tp_pl_flag case 4: codeless asms reading the num() result in r3 (uninitialised `register int asm("r3")`) give the arms' `addi r3,r30,ItemMgr@l` an anti-dependence so the `li` constants issue first (candidate #1)
})

# DOL structural pass 5 (2026-09-11)
MATCHING.update({
    "game/view.cpp": True,  # initPerspective: ONE frustum pointer `b` for both halves (the halves' `&b->point/normal[k]` are one gcse expression set: the second half's preheader addi order and the first half's single `&point[4]` PRE follow), `ViewSphere* s = &sphere` for the centre/radius stores (cse's find_best_addr rewrites `(mem s)` to `892(this)`, the rest stay `s`-based, s r18), `/ (2.0f * det)` inline (a fresh call-anchored pseudo), zfar stored before znear; two dead statics carry the .rodata 0x48..0x7f pools (STRIP_UNUSED); zero code
})

# DOL sweep 18b (2026-09-11)
MATCHING.update({
    "game/cam_qfps.cpp": True,  # move: the frustum copy loop counts with `j` (one allocno with the Draw_line3d loop's j: crosses the PSMTXMultVec calls -> callee-saved r29, sched2 hoists `j = nj` above the call), tail stores roll, fovy, reset last; setAreaData(CameraCut*): `p = &ofs[i][j]` before the flags test (cse rewrites the first store to `stwx r3,r28` = j-giv + outer i*132 giv), `for (j..; j++, k++)`; zero code
})

# DOL sweep 17 (2026-09-11)
MATCHING.update({
    "lib/builtin-delete.c": True,  # strings of SN's dead-stripped libstdc++ operator new/delete stubs (static bodies, LIBSN_UNITS strip)
})

# DOL sweep 18a (2026-09-11)
MATCHING.update({
    "game/esp09.cpp": True,  # PolyTrans: `pn = &w->pts[idx]` giv read by the Subtract argument, `p = pn` as an asm-emitted `mr` (cse canonical), idx-- between the p0/pp copies; two codeless "=m" asms with dead in-loop mentions rank p (17 refs) and pp (14 refs) above esp in global-alloc (candidate: global-alloc priority)
})

# DOL sweep 19b (2026-09-11)
MATCHING.update({
    "game/emwep.cpp": True,  # setCloth: statement order num, zeros, tables, owner, x38, floats (x48 before x50), `x54 = 0` LAST (the base register's death rides the zero store, so no float store is weight -1 and the 0.0 pseudo dies late enough for 0.6 to outrank it in local-alloc); emWepEscapeCamMove: the fovy store through `*(f32*)(u8*)&` (no MEM_IN_STRUCT_P: may alias the `pPL` load, whose chain then ranks `mr r29,r3; addi r31` above the pool `lis`es); zero code
})

# DOL sweep 20a (2026-09-11)
MATCHING.update({
    "game/mercenaries.cpp": True,  # GetSaveWork: `u32* tbl = SysRef(pSys)->x10; w = tbl[i]` -- the pointer local carries REG_POINTER, so regclass makes it the base of the `tbl[i]` address and i*4 the GENERAL index (r0, dying at the load); the rank-pointer giv init then issues second in sched2 (anti-dependence on the `clrlwi r0`) and takes r12; zero code
})

# DOL sweep 19a (2026-09-11)
MATCHING.update({
    "game/id_sys.cpp": True,  # set: the twelve `ofs -> pointer` diamonds store in BOTH arms (`if (a) u->x = (T)(a + data); else u->x = 0;`): jump2 cross-jumps the stores so the join block starts at `lwz pG` and the `c = 0` li (prio 2) ranks below it; zero code
    "game/roomdata.cpp": True,  # init: the total loop counts with `stage` (its `stage + 1` gets the lower gcse expression index, so the PRE'd increment is inserted before the hoisted `(u8) stage` and ofs/nx take r27/r26); linkRelData: `rel_no` read directly in the compare and the store (HImode load + one shared `clrlwi` for the compare and the DvdRead argument); zero code
    "game/objRobo.cpp": True,  # R0WalkBridge (zero code): the first flag test reads the word into a user variable (no cse jump threading past the second test, so the 0x80000000 `lis` stay per block and are not combined/hoisted), `hp` plain pointer for hitCnt (pG reloaded), `hp++, i++`, FRef(RoboFallSpdY); TaskSwitchFront/Back: `range = to` in the for-init, `range2 = from - to` in the up loop, no `base` copy, plus one tagged fr28 pin on `to` (#17) that keeps the for-init copy out of gcse cprop
})

# CRI pass 13 (2026-09-11)
MATCHING.update({
    "lib/gcci.c": True,  # per-handle `static inline gcci_ExecOne(GCCI ci)` (over, nbyte, p) + the table loop written twice (gcci_ExecServer(tbl) for gcCiReqRd, gcCiExecServer's own loop): the counter ranks above the induction pointer as an inlined local and below it as an own local, the CANCELED `over` redefinition takes over's register; `sctlen * (over / sctlen)`; pure C, no pins
})

# DOL sweep 21a (2026-09-11)
MATCHING.update({
    "game/sce_sys.cpp": True,  # ScenarioRoomInit: store order only -- the six byte zeros first (cse makes their QImode pseudo before any SImode zero exists; a later word zero's low part would replace it), eventCancel last of the six and pause last of the words (sched1 issues each group's dying store first), the byte group's `li`/stores ranked last by sched2's anti-dependence on the pG load's r9; zero code, the #13 asms removed
})

# CRI pass 14 (2026-09-11)
MATCHING.update({
    "lib/mpv_hdec.c": True,  # MPV_DecodePicAtrSj: the skip helpers assign `ptr` INSIDE the bitpos expression (a nested assignment blocks the forward substitution of the single-use bitpos, so it stays a variable coloured after ptr and above the AnalyUd call) and take the byte pointer as `(Uint8 *)(ptr + 1) + n` (codegen emits `(ptr + n) + 4` with the sum a backend temp above the ck.data reload); the same `(Uint8 *)(ptr - 2) + n` replaced the pass-7 asm `lwz data` pins in MPVHDEC_FLUSH/DecSlice; pure C
})

# DOL sweep 22a (2026-09-11)
MATCHING.update({
    "game/db_menu.cpp": True,  # move: GetGameTime declared with its real `u32` return (main_sub.h) -- the call then SETS r3, so the `addi r3,&h` argument move has one dependent (the call) instead of two (call + the next `lha r3`), ranks below `addi r4/r5` in sched1 and issues after the `subf`; zero code
    "game/emmine.cpp": True,  # R1_Shot/R1_ShotArrow: the no-info block's Effect*Delete tail written out (jump2 cross-jumps it into DELETE_EFFECT), so at sched1 the SndCall block runs through three more calls and its r7/r8 argument moves (never re-set) collect an anti-dependence from every later call: depend count r7/r8 4 > r4/r5/r6 3 > r3 2 gives the target order r7, r8, r5, r4, r6, r3; zero code
})

# DOL sweep 21b (2026-09-11)
MATCHING.update({
    "game/title.cpp": True,  # titleSub: every fade through FadeSetW (the colour pair is the inline's own BLKmode local at 32/36; in the `flags_54 & 0x40000000` arm cse rewrites the start address to the frame pseudo, `mr r4,r29` PRE'd, while `&col.end` stays a hard-reg-dest `addi r5,r1,36`); titleDebugMenu: one `int no` for case 3's checkRoomNo result and case 5's room (crosses the getPointNum calls -> r31 for both, the dbgPoint temp r30), the s8-parameter calls through int-view aliases (#4)
})

# DOL sweep 23b (2026-09-11)
MATCHING.update({
    "game/emrock.cpp": True,  # emRockDropCamMove: the `up` stores written BEFORE `len` -- after the six len loads the up.x store is the 34th memory insn of the block and sched1's 32-entry pending-list flush lands on it (every later memory insn anti-depends on it, the three pool highs swap r27..r29); zero code
})

# CRI pass 16b (2026-09-11)
MATCHING.update({
    "lib/sfx_cnv.c": True,  # CRI pass 16b: the LUMI table loop is a static helper defined before SFX_MakeTable (its 1.164f literal and int->float constant are created before MakeTable's strings; the inlined helper's `i` shares the zero `li` and takes r4) and the conversion is `(Uint8)(1.164f * ...)` without the (Sint32) cast (the fctiwz slot/FPR order); pure C
})

# CRI pass 17b (2026-09-11)
MATCHING.update({
    "lib/mpv_cmc.c": True,  # CRI pass 17b: the block tables addressed through an MPVCMC_OUTBLK struct pointer (`oi = ob->rt`: an addi off another addi is not folded by add-propagation), `work` local declared first
})

# DOL closer (2026-09-11)
MATCHING.update({
    "game/route_ck.cpp": True,  # Draw_rtp: the link loop's test refreshes a `GlobalWork* g` local, `i < ((RtpData*)(g = pG)->pRoomRtp)->nPoint` -- the pG value is ONE pseudo (g is referenced outside the copied exit test, so duplicate_loop_exit_test keeps it) whose PRE'd copies survive as `mr r11,r5` at the entry and the latch, and the body's `rtpData()` reload stays; zero code
})

# CRI pass 18b (2026-09-11)
MATCHING.update({
    "lib/adx_bsc.c": True,  # CRI pass 18b: EvokeDecode arms `pcm = pcmbuf; pcm += wr_pos` (pcmbuf is the in-place add destination = r6); `asm { add ofst, x70, ofst }` operand-order pins in ExecOneAdx/EvokeDecode (COMPILER-DIFF: M1)
    "lib/sfd_hds.c": True,  # CRI pass 18b: SFHDS_SetHdr hard pins p r28 / len r29 + sfh r31 in the inlined SFHDS_IsSfdHeader (the three physical neighbours lift result/sfd to the next level: result r30, sfd r27) (COMPILER-DIFF: M1); sfhds_DoProcessHdr fixed in pass 13 by per-site if/else locals for the vid ternaries
})

# DOL closer 3 (2026-09-11)
MATCHING.update({
    "game/shadow.cpp": True,  # make_comn_fit/parallel_light: `register u32 k asm("r11")` defined by a codeless asm fed by the 1.0 pool value and killed by a `"=m"(pos.x)` asm -- r11 is live between the 1.0 `lfs` and the conversion's `lfd`, so the fpmem loadaddr qty (ranked above the 1.0 high in local-alloc) cannot take r11 and the 1.0 high does (COMPILER-DIFF: 13)
})

# pendulum closer (2026-09-11)
MATCHING.update({
    "game/pendulum.cpp": True,  # PenClothMove/Move2/Move3: the final-loop AtCk diamond needs the jump2 cross-jump the other way round (AtCk tails merged, Border tails kept) -- codeless `asm("" : "+r"(hit))` anchors after each penClothAtCk call and after the if-arm's join, one macro line so rtx_renumbered_equal_p matches them; Move loop 2: `asm("" : "+f"(ang))` launder after `ang = 1.0f` keeps the `+ 1.0f` pool loads (loop.c combines the two into the preheader's fresh-high `lis r9; lfs f30`), and r5/r3/r4 argument pins + `asm("mr")` copy into `register Vec* pv asm("r28")` for the `addi r5,r1,0x38; mr r28,r5` PSVECSubtract shape (#3 frame-address PRE); tagged COMPILER-DIFF
})

# DOL closer 2: main_mem/motion/card/option/sce_com (2026-09-11)
MATCHING.update({
    "game/main_mem.cpp": True,  # MemCheckUsedHeap 143 -> 0, zero code: y0/y1 and `int x = 498` function-scope (x = REG_EQUIV constant rematerialised by reload before each `sth x0`, so the code constant's r0/r11 is reused), datactrl's tile store order (code, x0, y0, ...; r, g, b), `mt = &tile[0]` before the end-marker conversion, `hd = HeapHead + handle` for the cell loop
})

# CRI pass 19b (2026-09-11)
MATCHING.update({
    "lib/sfx_zmv.c": False,  # CRI pass 19b: 6/8, sfxzmv_MakeCnvZTbl 96 -> 12w (the helpers' src/dst declared dst-first and assigned src-first: src ranks above dst = r3/r4, tbl keeps its level-2 r31; left: the linear loops' copies in the guard block + one addi slot), MakeOrgZ32TblByCCIR 74w (the eight `i - k` computed up front in the target: a different DAG)
    "lib/cri_cvfs.c": False,  # CRI pass 19b: 11/13, cvFsGetFileSize 63 -> 45w (`tbl = cvfs_tbl` assigned after the default-device block), cvFsOpen 148 -> 152w (-4 bytes); the inlined cvfs_ResolveDev's tbl still hoisted above the strlen
    "lib/dct_ac.c": True,  # CRI pass 19b: DCT_AcInit 7 -> 0: the inner-loop row/column pointers are own variables declared below the asm .bss pool base (the frontend's range-split copies outranked the base, r29 -> r31), `addi ip, bss, __ArenaHi@l` = the pool-relative `addi 0` with a relocation (a literal 0 becomes `mr` in the backend's constant propagation); ldscript aliases _savefpr_27/_restfpr_27 (COMPILER-DIFF: M2)
})

# DOL final closer: at_mod/dvd/sce_at (2026-09-11)
MATCHING.update({
    "game/at_mod.cpp": True,  # ObaLineHitChk 9 -> 0: the `&p0` argument after getPartsPtr is an asm-emitted `addi %0,r1,8` (cse folds a C `&p0` into the copy address pseudo across the call through the beq AROUND path, COMPILER-DIFF: 12); the den f0 anchor takes `"f"(de * ef)` (ready one cycle later, so the hoisted `mr r3,r27` keeps its slot) plus a second `"f"(den)` reference (keeps den above the product in local-alloc, COMPILER-DIFF: 13)
    "game/dvd.cpp": True,  # DiscChange 7 -> 0, zero code: the first `pSys->region` read through a reference (`SysRef`, no MEM_SCALAR_P) is gated by all four game[] template stores in sched2, so the copy issues in template order 0,8,c,4
    "game/sce_at.cpp": True,  # sceAtGetItem 77 -> 0: `register u32 money asm("r29")` in case 8 (COMPILER-DIFF: 13, the it/ItemMgr-high/money rotation settles to r31/r30/r29), `int sel;` without initializer (cancel's zero is then the newest for `swep_flag = 0`, cancel lives from the top and ranks below sel: r29/r25), `put = 1` after `ItemMgr.use(&tmp)` (same as NoModel)
})

# esp08/esp18 closer (2026-09-11)
MATCHING.update({
    "game/esp18.cpp": True,  # Esp18_Trans 14 -> 0: `u32 i` declared before the `oy == zero` test (pseudo 237: gcse's PRE pseudos are numbered in hash-bucket order, so `i + 1` follows fp+0xc0 and the spill slots are 0x234/0x238 as in the target) + one codeless `asm("" : "=m"(inv[0][0]))` in the loop (the hoisted 1.0/0.5 REG_EQUIV constants tie at priority 171, older 0.5 coloured first; COMPILER-DIFF: candidate (loop.c insn_count))
    "game/esp08.cpp": True,  # Esp08_Trans/TransShimmer 143/143 -> 0 (shared ESP08_TILES macro): codeless `+f` launders on the four first-tile copies (cse1 promotes each copy to canonical and rewrites the mask quad, gcse/cse2 redo it; COMPILER-DIFF: first-tile copy canon), asm-emitted `fdivs` for the first tile's du/dv (the C divides block the fpu for 17 cycles and push the cu+du/cv+dv adds past the second y0 store, so reload inherits the y0 reload the original re-does; COMPILER-DIFF: asm-emitted fdivs), one `=m` keep-alive of y/st1 after the mask quad (f24/f21 global-alloc order), and zero-code statement order u0/dv/v0/du in the double loop's (j == numX-1, i != numY-1) arm (local-alloc f8/f9); .sdata padded to 8 (`asm(".section .sdata; .balign 8")`, the split object is 0x10)
})

# CRI pass 21 (2026-09-11)
MATCHING.update({
    "lib/sfd_tim.c": True,  # CRI pass 21: SFTIM_IsGetFrmTime 6 -> 0: a frame-taking copy of the inlined body (sftim_IsGetFrmTimeFrm) with `tunit` declared between `tscale` and `vrate` and read before `ftime` -- only a local of the same inlined body ranks between the body's locals (r10 between r9/r11); a wrapper local or the Tunit call's argument temporary ranks above them all
})

# cam_ctrl closer (2026-09-11)
MATCHING.update({
    "game/cam_ctrl.cpp": True,  # 84/84: HermiteExport 142 -> 0 zero code (`((u8*) &tmp)[n]` byte copies on one function-scope `n`, case 2/3 loads v,v0,v1, `cut->num - 1 == k`, pad loop on `j` with an in-place `rem`); cameraHitCheck 125 -> 0 (`do { } while (0)` LOOP_END anchor breaks cse1's ebb at the hit join, `register cAtariInfo* at asm("r29")` + launder so the copy loop runs on the ctor's `this` temp and `at` is not cprop'd, `hit = 0` after the p copy; COMPILER-DIFF); r0_RailBehind 3 -> 0 (asm `la` for the three VecLinearCombination pointer args, COMPILER-DIFF: #3)
})

# em_cloth closer (2026-09-11)
MATCHING.update({
    "game/em_cloth.cpp": True,  # Em18ClothSet 26 -> 0, pure C (the four codeless asms removed): the `if (a)` arm repeats `c->x40 = 0.1f; c->x44 = 4;` -- real uses for flow/sched1/regalloc (0.1 and 4 live across the branch: f11, callee-saved r28; the store weights and the 0.1 lfs priority follow), deleted by reload_cse_regs as no-op stores (reload_cse_noop_set_p: the MEM already holds the register) before sched2
})

# puzzle closer (2026-09-11)
MATCHING.update({
    "game/puzzle.cpp": True,  # 49/49: shape 1 -> 0 (pass 5): px enters the QImode multiplies as a one-byte `struct { s8 v; } w` -- a RECORD_TYPE local is not PROMOTE_MODEd, so `w.v` expands to an unpromoted REG:QI and expand_binop's "op1 REG, op0 not" commutative swap no longer fires for byte 2 of rot (the HImode extraction copied into a fresh QI REG); cse folds `(subreg:SI w)` to px, no instruction added; COMPILER-DIFF). movePiece/PutInCase/shape join per passes 1-4.
})

# cam_extra closer 2 (2026-09-11)
MATCHING.update({
    "game/cam_extra.cpp": True,  # 43/43 zero code, no tags. CameraBinocular ctor 17 -> 0 (`PlRef(pPL)->getPartsPtr` makes the pPL load wait for the member stores; dying-store order permuted), CameraPushObject::move 62 -> 0 (`getColumn(inv, 2, ..)` frame-offset-0 pointer shape, single VecAngle call, `!(a < b) && !(m >= c)` negated float tests), CameraBinocular::move 79 -> 0 (two-arm clamps cross-jumped, zoom clamp as a value, PlRef(pPL)->mat, orientation call after the mode block), CameraScope::move 91 -> 0 (Key.on & 0x10, angle_min/angle_max clamp, worldMat, `u8 c = sct--`, FRef(ytime)/FRef(xtime), Joy word-0 read, block-scoped cModel* pl), IdBinocular::move 271 -> 0 (getColumn(cam->mat, 2, &dir); `cnt` crosses no call: `unitPtr(cnt + 1)` + `cnt++` after the stores, cse makes the increment a copy of the call-crossing temp, so `li cnt,0/1` are anchored below the unitPtr calls and cnt takes the temp's r30 by copy preference; `i = cnt` for the while loop and the digit loop, block-scoped `k` for the unit loops; `MessageControl* mc = &cMes` after setLayout so `&mc->mes[1]` stays `addi 240` off a pseudo; FRef on every read of ratio/m/n with `u->v0 = FRef(ratio)` before `u->v1 = 1.0f`; scr2.x not scr3.x)
})
