#!/usr/bin/env python3
"""ProDG `ngccc -c` replacement: SN's cpp and ngcas through wibo, a native cc1/cc1plus.

Reproduces exactly what `ngccc.exe -v -c in -o out <flags> -lang=c++` runs:

  1. cpp.exe   -D__OPTIMIZE__ <-I/-D/-U> <fixed target/language defines> in -o tmp.i
               (plus -MD when --depfile is given: the header list, written in the same pass)
  2. cc1plus   <codegen flags> -quiet tmp.i -o tmp.s        <- native Linux build (SN v1.79 source)
  3. NgcAs.exe <-I> tmp.s -o out

Usage (as generated by configure.py / tools/project.py):
  ngccc.py --prodg-dir build/compilers/ProDG/3.9.3 --wrapper build/tools/wibo \
           --native-dir build/compilers/ProDG/3.9.3-v1.79 -c in.cpp -o out.o -O2 ... -lang=c++
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List

WIBO_TIMEOUT = 120  # seconds; a normal cpp/as run takes well under a second

TARGET_DEFS = [
    "-D__GNUC__=2",
    "-D__GNUC_MINOR__=95",
    "-D__NOASMPP__",
]
CXX_DEFS = ["-D__GNUG__=2", "-lang-c++", "-D__cplusplus"]
C_DEFS = ["-lang-c"]
MACHINE_DEFS = [
    "-DPPC",
    "-D__PPC__",
    "-D__PPC",
    "-Acpu(powerpc)",
    "-Amachine(powerpc)",
    "-D__CHAR_UNSIGNED__",
    "-D_BIG_ENDIAN",
    "-D__BIG_ENDIAN__",
    "-Amachine(bigendian)",
    "-D__PTRDIFF_TYPE__=int",
    "-D__SIZE_TYPE__=unsigned",
    "-D_CALL_SYSV",
    "-DSN_TARGET_NGC",
    "-D__SN__",
]
CXX_LANG_DEFS = ["-D_LANGUAGE_C_PLUS_PLUS", "-D__LANGUAGE_C_PLUS_PLUS"]
C_LANG_DEFS = ["-D_LANGUAGE_C", "-D__LANGUAGE_C", "-DLANGUAGE_C"]


def die(msg: str) -> None:
    print(f"ngccc.py: {msg}", file=sys.stderr)
    sys.exit(2)


def main(argv: List[str]) -> int:
    prodg_dir = wrapper = native_dir = None
    verbose = False
    save_asm = None  # --save-asm PATH: keep cc1's .s output (tools/asmcheck.py reads its #APP blocks)
    dep_path = None  # --depfile PATH: header list for ninja's "deps = gcc"

    lang = "c++"
    out_path = None
    inputs: List[str] = []
    cpp_flags: List[str] = []  # -I/-D/-U, attached form, in order
    inc_flags: List[str] = []  # -I only (ngcas gets these)
    cc1_flags: List[str] = []
    optimize = False

    args = list(argv)
    i = 0
    while i < len(args):
        a = args[i]
        i += 1
        if a == "--prodg-dir":
            prodg_dir = Path(args[i]); i += 1
        elif a == "--wrapper":
            wrapper = args[i]; i += 1
        elif a == "--native-dir":
            native_dir = Path(args[i]); i += 1
        elif a == "-c":
            pass
        elif a == "-v":
            verbose = True
        elif a == "--save-asm":
            save_asm = args[i]; i += 1
        elif a == "--depfile":
            dep_path = args[i]; i += 1
        elif a == "-o":
            out_path = args[i]; i += 1
        elif a.startswith("-lang="):
            lang = a[len("-lang="):]
        elif a in ("-I", "-D", "-U"):
            flag = a + args[i]; i += 1
            cpp_flags.append(flag)
            if a == "-I":
                inc_flags.append(flag)
        elif a.startswith(("-I", "-D", "-U")):
            cpp_flags.append(a)
            if a.startswith("-I"):
                inc_flags.append(a)
        elif a == "-G":
            # ngccc joins `-G 1024' into `-G1024' for cc1
            cc1_flags.append("-G" + args[i]); i += 1
        elif a.startswith("-"):
            if a.startswith("-O") and a != "-O0":
                optimize = True
            cc1_flags.append(a)
        else:
            inputs.append(a)

    if prodg_dir is None or wrapper is None or native_dir is None:
        die("--prodg-dir, --wrapper and --native-dir are required")
    if len(inputs) != 1 or out_path is None:
        die(f"expected exactly one input and -o, got {inputs} {out_path}")
    if lang not in ("c", "c++"):
        die(f"unsupported -lang={lang}")
    src = inputs[0]

    cpp_exe = prodg_dir / "CPP.exe"
    as_exe = prodg_dir / "NgcAs.exe"
    cc1_exe = native_dir / ("cc1plus" if lang == "c++" else "cc1")
    for p in (cpp_exe, as_exe, cc1_exe):
        if not p.exists():
            die(f"missing {p}")

    env = os.environ.copy()
    env["SN_NGC_PATH"] = str(prodg_dir)
    # mbchar/lexer behaviour must not depend on the host locale (the Windows build under
    # wibo runs in the "C" locale).
    env["LANG"] = "C"
    env["LC_ALL"] = "C"

    cpp_cmd = [wrapper, str(cpp_exe)]
    if optimize:
        cpp_cmd.append("-D__OPTIMIZE__")
    cpp_cmd += cpp_flags
    cpp_cmd += TARGET_DEFS
    cpp_cmd += CXX_DEFS if lang == "c++" else C_DEFS
    cpp_cmd += MACHINE_DEFS
    cpp_cmd += CXX_LANG_DEFS if lang == "c++" else C_LANG_DEFS

    stem = Path(src).stem
    with tempfile.TemporaryDirectory(prefix="ngccc.") as tmp:
        pre = os.path.join(tmp, stem + ".i")
        asm = os.path.join(tmp, stem + ".s")
        dep_tmp = os.path.join(tmp, stem + ".d")
        if dep_path:
            cpp_cmd += ["-MD", dep_tmp]

        cpp_cmd += [src, "-o", pre]
        cc1_cmd = [str(cc1_exe), *cc1_flags, "-quiet", pre, "-o", asm]
        as_cmd = [wrapper, str(as_exe), *inc_flags, asm, "-o", out_path]

        rel_module = next((f[len("-DREL_MODULE="):] for f in cpp_flags if f.startswith("-DREL_MODULE=")), None)

        def run(cmd) -> int:
            """wibo (NgcCpp/NgcAs) occasionally hangs at 0% CPU under load; a hung run never
            recovers, so kill it after WIBO_TIMEOUT seconds and retry."""
            if cmd[0] != wrapper:
                return subprocess.run(cmd, env=env).returncode
            for attempt in range(3):
                try:
                    return subprocess.run(cmd, env=env, timeout=WIBO_TIMEOUT).returncode
                except subprocess.TimeoutExpired:
                    print(f"ngccc: {Path(cmd[1]).name} hung for {WIBO_TIMEOUT}s, retry {attempt + 1}/3",
                          file=sys.stderr)
            die(f"{Path(cmd[1]).name} hung three times")

        def assemble(asm_path: str, obj_path: str) -> int:
            cmd = [wrapper, str(as_exe), *inc_flags, asm_path, "-o", obj_path]
            if verbose:
                print(" ".join(cmd), file=sys.stderr)
            return run(cmd)

        for cmd in (cpp_cmd, cc1_cmd, as_cmd):
            if verbose:
                print(" ".join(cmd), file=sys.stderr)
            rc = run(cmd)
            if rc != 0:
                if os.path.exists(out_path):
                    os.remove(out_path)
                return rc
            if cmd is cpp_cmd and dep_path:
                write_depfile(dep_tmp, dep_path, out_path)
            if cmd is cc1_cmd and save_asm:
                shutil.copyfile(asm, save_asm)
            if cmd is cc1_cmd and lang == "c++":
                if rel_module:
                    # module unit: `build/<ver>/src/<mod>/<stem>.o` -> `<mod>/<stem>.cpp`
                    unit = f"{rel_module}/{Path(out_path).stem}.cpp"
                    rc = place_linkonce_module(rel_module, unit, asm, os.path.join(tmp, stem + ".pre.o"), assemble)
                    if rc != 0:
                        return rc
                else:
                    place_linkonce(src, asm)
    return 0


def write_depfile(cpp_dep: str, out_dep: str, obj: str) -> None:
    """Turn cpp's dependency list into one ninja can use.

    Two things differ from what cpp writes: the target is the source's own name (`em.o`) where ninja
    needs the object path of the edge, and the headers come out absolute because the -I flags are.
    Paths inside the project are made relative so a generated header is the same node ninja builds.
    """
    root = str(Path(__file__).resolve().parent.parent) + os.sep
    with open(cpp_dep) as f:
        _, _, deps = f.read().partition(":")

    def fix(word: str) -> str:
        return os.path.relpath(word, root) if word.startswith(root) else word

    out = []
    for line in deps.splitlines(keepends=True):
        cont = line.endswith("\\\n")
        words = [fix(w) for w in line.rstrip("\\\n").split()]
        out.append(" " + " ".join(words) + (" \\\n" if cont else "\n"))

    os.makedirs(os.path.dirname(out_dep) or ".", exist_ok=True)
    with open(out_dep, "w") as f:
        f.write(obj + ":" + "".join(out))


def place_linkonce_module(module: str, unit: str, asm: str, pre_obj: str, assemble) -> int:
    """REL module unit: reproduce what the original `ngcld -r` link did with the linkonce functions.

    Evidence (every module with several objects including light.h, e.g. Sscrn ss_cap vs ss_main,
    t_emlist vs t_util/tools, st1_1 r101 vs r102.., em10's own partial link): the FIRST object of a
    module that instantiates a template function keeps that copy only if some relocation in the
    module references its symbol (cManager<cLight>::countActiveWork/create(int) are `bl`'d from the
    later objects' blocks, Widget<SUB_SCREEN>::quit/init/move from the vtables; `log`, `create()`,
    `create(int, u32)` are only ever called through vtables the DOL owns and vanish), while EVERY
    LATER object keeps all of its copies as nameless code (the 0x3B8 cLight blocks) whose calls
    resolve to the first object's copy. The `.sym` therefore names exactly the surviving first
    copies. So, per `.gnu.linkonce.t.<sym>` section of this unit (sizes tell the overloads apart,
    the .sym has no parameter lists):
      * named for this unit in the module sym_map          -> `.text` in place (keeps its symbol);
      * unnamed, and an earlier unit of the module names a function of the same class instance
        (the unit is a later instantiator of that class)   -> `.text` in place, definition made
        local (nameless duplicate; references to the symbol resolve to the first copy at link time);
      * unnamed, and this unit is the first one naming a function of the class instance (this unit
        is the class's first instantiator)                 -> deleted (unreferenced first copy);
      * unnamed, class instance named nowhere in the module -> kept nameless (a later duplicate is
        the common case; a first instantiator whose every member is unreferenced would be wrong,
        list it in modules.py LINKONCE_DROP).
    `.text` in place matters: the original interleaves the template bodies with
    __static_initialization_and_destruction_0 and the deferred inlines in emission order.
    The sections are decided from a first assembly of the unit (symbol sizes), then the asm is
    rewritten and assembled again by the caller.
    """
    root = Path(__file__).resolve().parent.parent
    ver = os.environ.get("RE4_VERSION", "G4BE08")
    sym_map = root / "config" / ver / "modules" / module / "sym_map.tsv"
    if not sym_map.exists():
        return 0
    sys.path.insert(0, str(root / "tools"))
    from sync_symbols import demangle_v2  # noqa: E402
    from elffile import Elf  # noqa: E402

    rows = set()                    # (name, size) of this unit's .text functions
    class_units = {}                # class instance -> {unit: first .text offset of that unit}
    unit_start = {}
    with open(sym_map) as f:
        next(f)
        for line in f:
            sec, off, size, u, scope, name, dn = line.rstrip("\n").split("\t")
            if sec != ".text":
                continue
            off = int(off, 16)
            unit_start[u] = min(unit_start.get(u, off), off)
            dn = dn if dn and dn != "." else name
            if u == unit:
                rows.add((dn, int(size, 16)))
                rows.add((name, int(size, 16)))
            if "::" in dn:
                class_units.setdefault(dn.rsplit("::", 1)[0], set()).add(u)
    if unit not in unit_start:
        return 0
    drop_list = set()
    try:
        sys.path.insert(0, str(root / "config" / ver))
        import modules as modules_mod  # noqa: E402
        drop_list = set(getattr(modules_mod, "LINKONCE_DROP", {}).get(unit, ()))
    except ImportError:
        pass

    rc = assemble(asm, pre_obj)
    if rc != 0:
        return rc
    elf = Elf(pre_obj)
    decision = {}  # section name -> ("named" | "dup" | "drop", symbol)
    for s in elf.sections:
        if not s.name.startswith(".gnu.linkonce.t."):
            continue
        funcs = [y for y in elf.symbols if y.shndx == s.index and y.type == 2 and y.name]
        if not funcs:
            continue
        sym = funcs[0]
        dn = demangle_v2(sym.name) or sym.name
        if sym.name in drop_list:
            decision[s.name] = ("drop", sym.name)
        elif (dn, sym.size) in rows or (sym.name, sym.size) in rows:
            decision[s.name] = ("named", sym.name)
        elif unit_start[unit] == min(unit_start.values()):
            # the module's first object: every linkonce copy here is a first copy, and an unreferenced
            # first copy vanished in the original link (the .sym names the referenced ones). The
            # single-unit enemy modules (em2e...) include light.h and get the 0x3B8 cManager<cLight>
            # block this way although their REL has none of it.
            decision[s.name] = ("drop", sym.name)
        else:
            cls = dn.rsplit("::", 1)[0] if "::" in dn else None
            users = class_units.get(cls, set()) if cls else set()
            earlier = [u for u in users if unit_start.get(u, 1 << 30) < unit_start[unit]]
            if earlier or unit not in users:
                decision[s.name] = ("dup", sym.name)
            else:
                decision[s.name] = ("drop", sym.name)

    out = []
    mode = None  # current linkonce decision while inside such a section
    with open(asm, encoding="latin-1") as f:
        for line in f:
            s = line.strip()
            if s.startswith(".section"):
                mode = None
                if s.startswith('.section\t".gnu.linkonce.t.'):
                    name = ".gnu.linkonce.t." + s[len('.section\t".gnu.linkonce.t.'):].split('"', 1)[0]
                    kind, sym = decision.get(name, ("dup", None))
                    mode = (kind, sym)
                    if kind == "drop":
                        continue
                    line = '\t.section\t".text"\n'
                elif s.startswith('.section\t".gnu.linkonce.d.'):
                    # vtables stay at their emission position in .rodata like in the DOL path
                    # (t_camera db_light: a deferred `static const Vec` and editColor's colour template
                    # follow the two vtables in the original .rodata; an appended copy puts them first)
                    line = '\t.section\t".rodata"\n'
            elif mode is not None:
                # inside the function: `.align/.weak/.type/label/.L_f*_s/body/.Lfe/.size`; the `.size`
                # line ends it (section-independent directives such as `.comm` may follow)
                kind, sym = mode
                ends = sym is not None and s.startswith(f".size\t {sym},")
                if ends:
                    mode = None
                if kind == "drop":
                    continue
                if kind == "dup" and sym is not None:
                    if s == f".weak\t{sym}" or s.startswith(f".type\t {sym},") or ends:
                        continue
                    if s == f"{sym}:":
                        line = f".Ldup.{sym}:\n"
            out.append(line)
    with open(asm, "w", encoding="latin-1") as f:
        f.writelines(out)
    return 0


def place_linkonce(src: str, asm: str) -> None:
    """Put the unit's own linkonce functions and every linkonce vtable back into .text / .rodata.

    The DOL keeps template instantiations, out-of-line inlines and synthesized destructors at the
    position the compiler emitted them (interleaved with __static_initialization_and_destruction_0
    and the global constructor thunks, vtables interleaved with the regular ones); a whole-section
    append cannot reproduce that. So the `.gnu.linkonce.t.<sym>` sections of functions sym_map.tsv
    lists for this unit become plain `.text` here, before assembling, and the `.gnu.linkonce.d.*`
    vtable sections become `.rodata` (the original linker kept every unit's copy). Unowned linkonce
    functions stay in their sections; tools/fold_linkonce.py drops them after assembling.
    """
    root = Path(__file__).resolve().parent.parent
    try:
        rel = Path(src).resolve().relative_to(root / "src")
    except ValueError:
        return
    sym_map = root / "config" / os.environ.get("RE4_VERSION", "G4BE08") / "sym_map.tsv"
    if not sym_map.exists():
        return
    sys.path.insert(0, str(root / "tools"))
    from fold_linkonce import unit_text_functions  # noqa: E402
    from sync_symbols import demangle_v2  # noqa: E402

    owned, foreign = unit_text_functions(rel.as_posix())
    out = []
    with open(asm, encoding="latin-1") as f:
        for line in f:
            s = line.strip()
            if s.startswith('.section\t".gnu.linkonce.t.'):
                name = s[len('.section\t".gnu.linkonce.t.'):].split('"', 1)[0]
                if (demangle_v2(name) or name) in owned and name not in foreign:
                    line = '\t.section\t".text"\n'
            elif s.startswith('.section\t".gnu.linkonce.d.'):
                line = '\t.section\t".rodata"\n'
            elif s in (".section\t.ctors", ".section\t.dtors"):
                # the split objects carry their constructor pointers in `.ctor` / `.dtor`; the
                # linker script collects those in input (address) order, so the compiled unit's
                # entry lands in the same slot only under the same section name
                line = "\t.section\t" + s.split("\t")[1][:-1] + '\n'
            out.append(line)
    with open(asm, "w", encoding="latin-1") as f:
        f.writelines(out)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
