#!/usr/bin/env python3
"""ProDG `ngccc -c` replacement: SN's cpp and ngcas through wibo, a native cc1/cc1plus.

Reproduces exactly what `ngccc.exe -v -c in -o out <flags> -lang=c++` runs:

  1. cpp.exe   -D__OPTIMIZE__ <-I/-D/-U> <fixed target/language defines> in -o tmp.i
  2. cc1plus   <codegen flags> -quiet tmp.i -o tmp.s        <- native Linux build (SN v1.79 source)
  3. NgcAs.exe <-I> tmp.s -o out

Usage (as generated by configure.py / tools/project.py):
  ngccc.py --prodg-dir build/compilers/ProDG/3.9.3 --wrapper build/tools/wibo \
           --native-dir build/compilers/ProDG/3.9.3-v1.79 -c in.cpp -o out.o -O2 ... -lang=c++
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List

TARGET_DEFS = [
    "-D__GNUC__=2",
    "-D__GNUC_MINOR__=95",
    "-D__NOASMPP__",
]
CXX_DEFS = ["-D__GNUG__=2", "-lang-c++", "-D__cplusplus"]
C_DEFS = ["-lang-c"]
MACHINE_DEFS = [
    "-DPPC",
    "-D__PPC__",
    "-D__PPC",
    "-Acpu(powerpc)",
    "-Amachine(powerpc)",
    "-D__CHAR_UNSIGNED__",
    "-D_BIG_ENDIAN",
    "-D__BIG_ENDIAN__",
    "-Amachine(bigendian)",
    "-D__PTRDIFF_TYPE__=int",
    "-D__SIZE_TYPE__=unsigned",
    "-D_CALL_SYSV",
    "-DSN_TARGET_NGC",
    "-D__SN__",
]
CXX_LANG_DEFS = ["-D_LANGUAGE_C_PLUS_PLUS", "-D__LANGUAGE_C_PLUS_PLUS"]
C_LANG_DEFS = ["-D_LANGUAGE_C", "-D__LANGUAGE_C", "-DLANGUAGE_C"]


def die(msg: str) -> None:
    print(f"ngccc.py: {msg}", file=sys.stderr)
    sys.exit(2)


def main(argv: List[str]) -> int:
    prodg_dir = wrapper = native_dir = None
    verbose = False
    lang = "c++"
    out_path = None
    inputs: List[str] = []
    cpp_flags: List[str] = []  # -I/-D/-U, attached form, in order
    inc_flags: List[str] = []  # -I only (ngcas gets these)
    cc1_flags: List[str] = []
    optimize = False

    args = list(argv)
    i = 0
    while i < len(args):
        a = args[i]
        i += 1
        if a == "--prodg-dir":
            prodg_dir = Path(args[i]); i += 1
        elif a == "--wrapper":
            wrapper = args[i]; i += 1
        elif a == "--native-dir":
            native_dir = Path(args[i]); i += 1
        elif a == "-c":
            pass
        elif a == "-v":
            verbose = True
        elif a == "-o":
            out_path = args[i]; i += 1
        elif a.startswith("-lang="):
            lang = a[len("-lang="):]
        elif a in ("-I", "-D", "-U"):
            flag = a + args[i]; i += 1
            cpp_flags.append(flag)
            if a == "-I":
                inc_flags.append(flag)
        elif a.startswith(("-I", "-D", "-U")):
            cpp_flags.append(a)
            if a.startswith("-I"):
                inc_flags.append(a)
        elif a == "-G":
            # ngccc joins `-G 1024' into `-G1024' for cc1
            cc1_flags.append("-G" + args[i]); i += 1
        elif a.startswith("-"):
            if a.startswith("-O") and a != "-O0":
                optimize = True
            cc1_flags.append(a)
        else:
            inputs.append(a)

    if prodg_dir is None or wrapper is None or native_dir is None:
        die("--prodg-dir, --wrapper and --native-dir are required")
    if len(inputs) != 1 or out_path is None:
        die(f"expected exactly one input and -o, got {inputs} {out_path}")
    if lang not in ("c", "c++"):
        die(f"unsupported -lang={lang}")
    src = inputs[0]

    cpp_exe = prodg_dir / "CPP.exe"
    as_exe = prodg_dir / "NgcAs.exe"
    cc1_exe = native_dir / ("cc1plus" if lang == "c++" else "cc1")
    for p in (cpp_exe, as_exe, cc1_exe):
        if not p.exists():
            die(f"missing {p}")

    env = os.environ.copy()
    env["SN_NGC_PATH"] = str(prodg_dir)
    # mbchar/lexer behaviour must not depend on the host locale (the Windows build under
    # wibo runs in the "C" locale).
    env["LANG"] = "C"
    env["LC_ALL"] = "C"

    cpp_cmd = [wrapper, str(cpp_exe)]
    if optimize:
        cpp_cmd.append("-D__OPTIMIZE__")
    cpp_cmd += cpp_flags
    cpp_cmd += TARGET_DEFS
    cpp_cmd += CXX_DEFS if lang == "c++" else C_DEFS
    cpp_cmd += MACHINE_DEFS
    cpp_cmd += CXX_LANG_DEFS if lang == "c++" else C_LANG_DEFS

    stem = Path(src).stem
    with tempfile.TemporaryDirectory(prefix="ngccc.") as tmp:
        pre = os.path.join(tmp, stem + ".i")
        asm = os.path.join(tmp, stem + ".s")

        cpp_cmd += [src, "-o", pre]
        cc1_cmd = [str(cc1_exe), *cc1_flags, "-quiet", pre, "-o", asm]
        as_cmd = [wrapper, str(as_exe), *inc_flags, asm, "-o", out_path]

        for cmd in (cpp_cmd, cc1_cmd, as_cmd):
            if verbose:
                print(" ".join(cmd), file=sys.stderr)
            rc = subprocess.run(cmd, env=env).returncode
            if rc != 0:
                if os.path.exists(out_path):
                    os.remove(out_path)
                return rc
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
